// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// ActiveDirectory is the public representation of the active directory config.
public struct ActiveDirectory: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Identifier. The resource name of the active directory.
  /// Format:
  /// `projects/{project_number}/locations/{location_id}/activeDirectories/{active_directory_id}`.
  public var name: Swift.String = Swift.String()

  /// Output only. Create time of the active directory.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The state of the AD.
  public var state: ActiveDirectory.State = ActiveDirectory.State()

  /// Required. Name of the Active Directory domain
  public var domain: Swift.String = Swift.String()

  /// The Active Directory site the service will limit Domain Controller
  /// discovery too.
  public var site: Swift.String = Swift.String()

  /// Required. Comma separated list of DNS server IP addresses for the Active
  /// Directory domain.
  public var dns: Swift.String = Swift.String()

  /// Required. NetBIOSPrefix is used as a prefix for SMB server name.
  public var netBiosPrefix: Swift.String = Swift.String()

  /// The Organizational Unit (OU) within the Windows Active Directory the user
  /// belongs to.
  public var organizationalUnit: Swift.String = Swift.String()

  /// If enabled, AES encryption will be enabled for SMB communication.
  public var aesEncryption: Swift.Bool = Swift.Bool()

  /// Required. Username of the Active Directory domain administrator.
  public var username: Swift.String = Swift.String()

  /// Required. Password of the Active Directory domain administrator.
  public var password: Swift.String = Swift.String()

  /// Optional. Users to be added to the Built-in Backup Operator active
  /// directory group.
  public var backupOperators: [Swift.String] = []

  /// Optional. Users to be added to the Built-in Admininstrators group.
  public var administrators: [Swift.String] = []

  /// Optional. Domain users to be given the SeSecurityPrivilege.
  public var securityOperators: [Swift.String] = []

  /// Name of the active directory machine. This optional parameter is used only
  /// while creating kerberos volume
  public var kdcHostname: Swift.String = Swift.String()

  /// KDC server IP address for the active directory machine.
  public var kdcIp: Swift.String = Swift.String()

  /// If enabled, will allow access to local users and LDAP users. If access is
  /// needed for only LDAP users, it has to be disabled.
  public var nfsUsersWithLdap: Swift.Bool = Swift.Bool()

  /// Description of the active directory.
  public var description: Swift.String = Swift.String()

  /// Specifies whether or not the LDAP traffic needs to be signed.
  public var ldapSigning: Swift.Bool = Swift.Bool()

  /// If enabled, traffic between the SMB server to Domain Controller (DC) will
  /// be encrypted.
  public var encryptDcConnections: Swift.Bool = Swift.Bool()

  /// Labels for the active directory.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. The state details of the Active Directory.
  public var stateDetails: Swift.String = Swift.String()

  /// Initialize a new instance of `ActiveDirectory`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ActiveDirectory().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The Active Directory States
  public enum State: Codable, Equatable, Sendable {
    /// Unspecified Active Directory State
    case unspecified
    /// Active Directory State is Creating
    case creating
    /// Active Directory State is Ready
    case ready
    /// Active Directory State is Updating
    case updating
    /// Active Directory State is In use
    case inUse
    /// Active Directory State is Deleting
    case deleting
    /// Active Directory State is Error
    case error
    /// Active Directory State is Diagnosing.
    case diagnosing
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .ready: return 2
      case .updating: return 3
      case .inUse: return 4
      case .deleting: return 5
      case .error: return 6
      case .diagnosing: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .ready: return "READY"
      case .updating: return "UPDATING"
      case .inUse: return "IN_USE"
      case .deleting: return "DELETING"
      case .error: return "ERROR"
      case .diagnosing: return "DIAGNOSING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "READY": self = .ready
      case "UPDATING": self = .updating
      case "IN_USE": self = .inUse
      case "DELETING": self = .deleting
      case "ERROR": self = .error
      case "DIAGNOSING": self = .diagnosing
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .ready
      case 3: self = .updating
      case 4: self = .inUse
      case 5: self = .deleting
      case 6: self = .error
      case 7: self = .diagnosing
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .creating: return try container.encode(1)
      case .ready: return try container.encode(2)
      case .updating: return try container.encode(3)
      case .inUse: return try container.encode(4)
      case .deleting: return try container.encode(5)
      case .error: return try container.encode(6)
      case .diagnosing: return try container.encode(7)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.netapp.v1.ActiveDirectory"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
