// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A NetApp BackupVault.
public struct BackupVault: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Identifier. The resource name of the backup vault.
  /// Format:
  /// `projects/{project_id}/locations/{location}/backupVaults/{backup_vault_id}`.
  public var name: Swift.String = Swift.String()

  /// Output only. The backup vault state.
  public var state: BackupVault.State = BackupVault.State()

  /// Output only. Create time of the backup vault.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Description of the backup vault.
  public var description: Swift.String = Swift.String()

  /// Resource labels to represent user provided metadata.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. Type of backup vault to be created.
  /// Default is IN_REGION.
  public var backupVaultType: BackupVault.BackupVaultType = BackupVault.BackupVaultType()

  /// Output only. Region in which the backup vault is created.
  /// Format: `projects/{project_id}/locations/{location}`
  public var sourceRegion: Swift.String = Swift.String()

  /// Optional. Region where the backups are stored.
  /// Format: `projects/{project_id}/locations/{location}`
  public var backupRegion: Swift.String = Swift.String()

  /// Output only. Name of the Backup vault created in source region.
  /// Format:
  /// `projects/{project_id}/locations/{location}/backupVaults/{backup_vault_id}`
  public var sourceBackupVault: Swift.String = Swift.String()

  /// Output only. Name of the Backup vault created in backup region.
  /// Format:
  /// `projects/{project_id}/locations/{location}/backupVaults/{backup_vault_id}`
  public var destinationBackupVault: Swift.String = Swift.String()

  /// Optional. Backup retention policy defining the retention of backups.
  public var backupRetentionPolicy: BackupVault.BackupRetentionPolicy? = nil

  /// Optional. Specifies the Key Management System (KMS) configuration to be
  /// used for backup encryption. Format:
  /// `projects/{project}/locations/{location}/kmsConfigs/{kms_config}`
  public var kmsConfig: Swift.String = Swift.String()

  /// Output only. Field indicating encryption state of CMEK backups.
  public var encryptionState: BackupVault.EncryptionState = BackupVault.EncryptionState()

  /// Output only. The crypto key version used to encrypt the backup vault.
  /// Format:
  /// `projects/{project}/locations/{location}/keyRings/{key_ring}/cryptoKeys/{crypto_key}/cryptoKeyVersions/{crypto_key_version}`
  public var backupsCryptoKeyVersion: Swift.String = Swift.String()

  /// Initialize a new instance of `BackupVault`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BackupVault().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Retention policy for backups in the backup vault
  public struct BackupRetentionPolicy: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. Minimum retention duration in days for backups in the backup
    /// vault.
    public var backupMinimumEnforcedRetentionDays: Swift.Int32 = Swift.Int32()

    /// Optional. Indicates if the daily backups are immutable.
    /// At least one of daily_backup_immutable, weekly_backup_immutable,
    /// monthly_backup_immutable and manual_backup_immutable must be true.
    public var dailyBackupImmutable: Swift.Bool = Swift.Bool()

    /// Optional. Indicates if the weekly backups are immutable.
    /// At least one of daily_backup_immutable, weekly_backup_immutable,
    /// monthly_backup_immutable and manual_backup_immutable must be true.
    public var weeklyBackupImmutable: Swift.Bool = Swift.Bool()

    /// Optional. Indicates if the monthly backups are immutable.
    /// At least one of daily_backup_immutable, weekly_backup_immutable,
    /// monthly_backup_immutable and manual_backup_immutable must be true.
    public var monthlyBackupImmutable: Swift.Bool = Swift.Bool()

    /// Optional. Indicates if the manual backups are immutable.
    /// At least one of daily_backup_immutable, weekly_backup_immutable,
    /// monthly_backup_immutable and manual_backup_immutable must be true.
    public var manualBackupImmutable: Swift.Bool = Swift.Bool()

    /// Initialize a new instance of `BackupRetentionPolicy`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = BackupRetentionPolicy().with { $0.backupMinimumEnforcedRetentionDays = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.netapp.v1.BackupVault.BackupRetentionPolicy"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// The Backup Vault States
  public enum State: Codable, Equatable, Sendable {
    /// State not set.
    case unspecified
    /// BackupVault is being created.
    case creating
    /// BackupVault is available for use.
    case ready
    /// BackupVault is being deleted.
    case deleting
    /// BackupVault is not valid and cannot be used.
    case error
    /// BackupVault is being updated.
    case updating
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .ready: return 2
      case .deleting: return 3
      case .error: return 4
      case .updating: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .ready: return "READY"
      case .deleting: return "DELETING"
      case .error: return "ERROR"
      case .updating: return "UPDATING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "READY": self = .ready
      case "DELETING": self = .deleting
      case "ERROR": self = .error
      case "UPDATING": self = .updating
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .ready
      case 3: self = .deleting
      case 4: self = .error
      case 5: self = .updating
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .creating: return try container.encode(1)
      case .ready: return try container.encode(2)
      case .deleting: return try container.encode(3)
      case .error: return try container.encode(4)
      case .updating: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Backup Vault Type.
  public enum BackupVaultType: Codable, Equatable, Sendable {
    /// BackupVault type not set.
    case unspecified
    /// BackupVault type is IN_REGION.
    case inRegion
    /// BackupVault type is CROSS_REGION.
    case crossRegion
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .inRegion: return 1
      case .crossRegion: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "BACKUP_VAULT_TYPE_UNSPECIFIED"
      case .inRegion: return "IN_REGION"
      case .crossRegion: return "CROSS_REGION"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:BackupVaultType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "BACKUP_VAULT_TYPE_UNSPECIFIED": self = .unspecified
      case "IN_REGION": self = .inRegion
      case "CROSS_REGION": self = .crossRegion
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:BackupVaultType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .inRegion
      case 2: self = .crossRegion
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .inRegion: return try container.encode(1)
      case .crossRegion: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Encryption state of customer-managed encryption keys (CMEK) backups.
  public enum EncryptionState: Codable, Equatable, Sendable {
    /// Encryption state not set.
    case unspecified
    /// Encryption state is pending.
    case pending
    /// Encryption is complete.
    case completed
    /// Encryption is in progress.
    case inProgress
    /// Encryption has failed.
    case failed
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .pending: return 1
      case .completed: return 2
      case .inProgress: return 3
      case .failed: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ENCRYPTION_STATE_UNSPECIFIED"
      case .pending: return "ENCRYPTION_STATE_PENDING"
      case .completed: return "ENCRYPTION_STATE_COMPLETED"
      case .inProgress: return "ENCRYPTION_STATE_IN_PROGRESS"
      case .failed: return "ENCRYPTION_STATE_FAILED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:EncryptionState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ENCRYPTION_STATE_UNSPECIFIED": self = .unspecified
      case "ENCRYPTION_STATE_PENDING": self = .pending
      case "ENCRYPTION_STATE_COMPLETED": self = .completed
      case "ENCRYPTION_STATE_IN_PROGRESS": self = .inProgress
      case "ENCRYPTION_STATE_FAILED": self = .failed
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:EncryptionState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .pending
      case 2: self = .completed
      case 3: self = .inProgress
      case 4: self = .failed
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .pending: return try container.encode(1)
      case .completed: return try container.encode(2)
      case .inProgress: return try container.encode(3)
      case .failed: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.netapp.v1.BackupVault"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
