// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Backup Policy.
public struct BackupPolicy: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Identifier. The resource name of the backup policy.
  /// Format:
  /// `projects/{project_id}/locations/{location}/backupPolicies/{backup_policy_id}`.
  public var name: Swift.String = Swift.String()

  /// Number of daily backups to keep. Note that the minimum daily backup limit
  /// is 2.
  public var dailyBackupLimit: Swift.Int32? = nil

  /// Number of weekly backups to keep. Note that the sum of daily, weekly and
  /// monthly backups should be greater than 1.
  public var weeklyBackupLimit: Swift.Int32? = nil

  /// Number of monthly backups to keep. Note that the sum of daily, weekly and
  /// monthly backups should be greater than 1.
  public var monthlyBackupLimit: Swift.Int32? = nil

  /// Description of the backup policy.
  public var description: Swift.String? = nil

  /// If enabled, make backups automatically according to the schedules.
  /// This will be applied to all volumes that have this policy attached and
  /// enforced on volume level. If not specified, default is true.
  public var enabled: Swift.Bool? = nil

  /// Output only. The total number of volumes assigned by this backup policy.
  public var assignedVolumeCount: Swift.Int32? = nil

  /// Output only. The time when the backup policy was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Resource labels to represent user provided metadata.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. The backup policy state.
  public var state: BackupPolicy.State = BackupPolicy.State()

  /// Initialize a new instance of `BackupPolicy`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BackupPolicy().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public enum State: Codable, Equatable, Sendable {
    /// State not set.
    case unspecified
    /// BackupPolicy is being created.
    case creating
    /// BackupPolicy is available for use.
    case ready
    /// BackupPolicy is being deleted.
    case deleting
    /// BackupPolicy is not valid and cannot be used.
    case error
    /// BackupPolicy is being updated.
    case updating
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .ready: return 2
      case .deleting: return 3
      case .error: return 4
      case .updating: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .ready: return "READY"
      case .deleting: return "DELETING"
      case .error: return "ERROR"
      case .updating: return "UPDATING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "READY": self = .ready
      case "DELETING": self = .deleting
      case "ERROR": self = .error
      case "UPDATING": self = .updating
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .ready
      case 3: self = .deleting
      case 4: self = .error
      case 5: self = .updating
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .creating: return try container.encode(1)
      case .ready: return try container.encode(2)
      case .deleting: return try container.encode(3)
      case .error: return try container.encode(4)
      case .updating: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.netapp.v1.BackupPolicy"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
