// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A NetApp Backup.
public struct Backup: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. The resource name of the backup.
  /// Format:
  /// `projects/{project_id}/locations/{location}/backupVaults/{backup_vault_id}/backups/{backup_id}`.
  public var name: Swift.String = Swift.String()

  /// Output only. The backup state.
  public var state: Backup.State = Backup.State()

  /// A description of the backup with 2048 characters or less.
  /// Requests with longer descriptions will be rejected.
  public var description: Swift.String = Swift.String()

  /// Output only. Size of the file system when the backup was created. When
  /// creating a new volume from the backup, the volume capacity will have to be
  /// at least as big.
  public var volumeUsageBytes: Swift.Int64 = Swift.Int64()

  /// Output only. Type of backup, manually created or created by a backup
  /// policy.
  public var backupType: Backup.Type_ = Backup.Type_()

  /// Volume full name of this backup belongs to.
  /// Either source_volume or ontap_source should be provided.
  /// Format:
  /// `projects/{projects_id}/locations/{location}/volumes/{volume_id}`
  public var sourceVolume: Swift.String = Swift.String()

  /// If specified, backup will be created from the given snapshot.
  /// If not specified, there will be a new snapshot taken to initiate the backup
  /// creation. Format:
  /// `projects/{project_id}/locations/{location}/volumes/{volume_id}/snapshots/{snapshot_id}`
  public var sourceSnapshot: Swift.String? = nil

  /// Output only. The time when the backup was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Resource labels to represent user provided metadata.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. Total size of all backups in a chain in bytes = baseline
  /// backup size + sum(incremental backup size)
  public var chainStorageBytes: Swift.Int64 = Swift.Int64()

  /// Output only. Reserved for future use
  public var satisfiesPzs: Swift.Bool = Swift.Bool()

  /// Output only. Reserved for future use
  public var satisfiesPzi: Swift.Bool = Swift.Bool()

  /// Output only. Region of the volume from which the backup was created.
  /// Format: `projects/{project_id}/locations/{location}`
  public var volumeRegion: Swift.String = Swift.String()

  /// Output only. Region in which backup is stored.
  /// Format: `projects/{project_id}/locations/{location}`
  public var backupRegion: Swift.String = Swift.String()

  /// Output only. The time until which the backup is not deletable.
  public var enforcedRetentionEndTime: GoogleWKT.WKTTimestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Backup`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Backup().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let state = CodingKeys(stringValue: "state")
    static let description = CodingKeys(stringValue: "description")
    static let volumeUsageBytes = CodingKeys(stringValue: "volumeUsageBytes")
    static let backupType = CodingKeys(stringValue: "backupType")
    static let sourceVolume = CodingKeys(stringValue: "sourceVolume")
    static let sourceSnapshot = CodingKeys(stringValue: "sourceSnapshot")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let chainStorageBytes = CodingKeys(stringValue: "chainStorageBytes")
    static let satisfiesPzs = CodingKeys(stringValue: "satisfiesPzs")
    static let satisfiesPzi = CodingKeys(stringValue: "satisfiesPzi")
    static let volumeRegion = CodingKeys(stringValue: "volumeRegion")
    static let backupRegion = CodingKeys(stringValue: "backupRegion")
    static let enforcedRetentionEndTime = CodingKeys(stringValue: "enforcedRetentionEndTime")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "state",
      "description",
      "volumeUsageBytes",
      "backupType",
      "sourceVolume",
      "sourceSnapshot",
      "createTime",
      "labels",
      "chainStorageBytes",
      "satisfiesPzs",
      "satisfiesPzi",
      "volumeRegion",
      "backupRegion",
      "enforcedRetentionEndTime",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Backup.State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .volumeUsageBytes) {
      self.volumeUsageBytes = value
    }
    if let value = try container.decodeIfPresent(Backup.Type_.self, forKey: .backupType) {
      self.backupType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sourceVolume) {
      self.sourceVolume = value
    }
    self.sourceSnapshot = try container.decodeIfPresent(Swift.String.self, forKey: .sourceSnapshot)
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .chainStorageBytes) {
      self.chainStorageBytes = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .satisfiesPzs) {
      self.satisfiesPzs = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .satisfiesPzi) {
      self.satisfiesPzi = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .volumeRegion) {
      self.volumeRegion = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .backupRegion) {
      self.backupRegion = value
    }
    self.enforcedRetentionEndTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .enforcedRetentionEndTime)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.volumeUsageBytes, forKey: .volumeUsageBytes)
    try container.encode(self.backupType, forKey: .backupType)
    try container.encode(self.sourceVolume, forKey: .sourceVolume)
    try container.encodeIfPresent(self.sourceSnapshot, forKey: .sourceSnapshot)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.chainStorageBytes, forKey: .chainStorageBytes)
    try container.encode(self.satisfiesPzs, forKey: .satisfiesPzs)
    try container.encode(self.satisfiesPzi, forKey: .satisfiesPzi)
    try container.encode(self.volumeRegion, forKey: .volumeRegion)
    try container.encode(self.backupRegion, forKey: .backupRegion)
    try container.encodeIfPresent(self.enforcedRetentionEndTime, forKey: .enforcedRetentionEndTime)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The Backup States
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Sendable {
    /// State not set.
    case unspecified
    /// Backup is being created. While in this state, the snapshot for the backup
    /// point-in-time may not have been created yet, and so the point-in-time may
    /// not have been fixed.
    case creating
    /// Backup is being uploaded. While in this state, none of the writes to the
    /// volume will be included in the backup.
    case uploading
    /// Backup is available for use.
    case ready
    /// Backup is being deleted.
    case deleting
    /// Backup is not valid and cannot be used for creating new volumes or
    /// restoring existing volumes.
    case error
    /// Backup is being updated.
    case updating
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .uploading: return 2
      case .ready: return 3
      case .deleting: return 4
      case .error: return 5
      case .updating: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .uploading: return "UPLOADING"
      case .ready: return "READY"
      case .deleting: return "DELETING"
      case .error: return "ERROR"
      case .updating: return "UPDATING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "UPLOADING": self = .uploading
      case "READY": self = .ready
      case "DELETING": self = .deleting
      case "ERROR": self = .error
      case "UPDATING": self = .updating
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .uploading
      case 3: self = .ready
      case 4: self = .deleting
      case 5: self = .error
      case 6: self = .updating
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .creating: return try container.encode("CREATING")
      case .uploading: return try container.encode("UPLOADING")
      case .ready: return try container.encode("READY")
      case .deleting: return try container.encode("DELETING")
      case .error: return try container.encode("ERROR")
      case .updating: return try container.encode("UPDATING")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Backup types.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Type_: Codable, Equatable, Sendable {
    /// Unspecified backup type.
    case unspecified
    /// Manual backup type.
    case manual
    /// Scheduled backup type.
    case scheduled
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .manual: return 1
      case .scheduled: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TYPE_UNSPECIFIED"
      case .manual: return "MANUAL"
      case .scheduled: return "SCHEDULED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Type_/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TYPE_UNSPECIFIED": self = .unspecified
      case "MANUAL": self = .manual
      case "SCHEDULED": self = .scheduled
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Type_/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .manual
      case 2: self = .scheduled
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("TYPE_UNSPECIFIED")
      case .manual: return try container.encode("MANUAL")
      case .scheduled: return try container.encode("SCHEDULED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.netapp.v1.Backup"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
