// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// BackupConfig contains backup related config on a volume.
public struct BackupConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Optional. When specified, schedule backups will be created based on the
  /// policy configuration.
  public var backupPolicies: [Swift.String] = []

  /// Optional. Name of backup vault.
  /// Format:
  /// projects/{project_id}/locations/{location}/backupVaults/{backup_vault_id}
  public var backupVault: Swift.String = Swift.String()

  /// Optional. When set to true, scheduled backup is enabled on the volume.
  /// This field should be nil when there's no backup policy attached.
  public var scheduledBackupEnabled: Swift.Bool? = nil

  /// Output only. Total size of all backups in a chain in bytes = baseline
  /// backup size + sum(incremental backup size).
  public var backupChainBytes: Swift.Int64? = nil

  /// Initialize a new instance of `BackupConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BackupConfig().with { $0.backupPolicies = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.netapp.v1.BackupConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
