// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Block device represents the device(s) which are stored in the block volume.
public struct BlockDevice: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. User-defined name for the block device, unique within the volume.
  /// In case no user input is provided, name will be auto-generated in the
  /// backend. The name must meet the following requirements:
  /// *   Be between 1 and 255 characters long.
  /// *   Contain only uppercase or lowercase letters (A-Z, a-z), numbers (0-9),
  ///     and the following special characters: "-", "_", "}", "{", ".".
  /// *   Spaces are not allowed.
  public var name: Swift.String? = nil

  /// Optional. A list of host groups that identify hosts that can mount the
  /// block volume. Format:
  /// `projects/{project_id}/locations/{location}/hostGroups/{host_group_id}`
  /// This field can be updated after the block device is created.
  public var hostGroups: [Swift.String] = []

  /// Output only. Device identifier of the block volume. This represents
  /// `lun_serial_number` for iSCSI volumes.
  public var identifier: Swift.String = Swift.String()

  /// Optional. The size of the block device in GiB.
  /// Any value provided for the `size_gib` field during volume creation is
  /// ignored. The block device's size is system-managed and will be set to match
  /// the parent Volume's `capacity_gib`.
  public var sizeGib: Swift.Int64? = nil

  /// Required. Immutable. The OS type of the volume.
  /// This field can't be changed after the block device is created.
  public var osType: OsType = OsType()

  /// Initialize a new instance of `BlockDevice`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BlockDevice().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.netapp.v1.BlockDevice"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
