// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Cache Parameters for the volume.
public struct CacheParameters: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Name of the origin volume for the cache volume.
  public var peerVolumeName: Swift.String = Swift.String()

  /// Required. Name of the origin volume's ONTAP cluster.
  public var peerClusterName: Swift.String = Swift.String()

  /// Required. Name of the origin volume's SVM.
  public var peerSvmName: Swift.String = Swift.String()

  /// Required. List of IC LIF addresses of the origin volume's ONTAP cluster.
  public var peerIpAddresses: [Swift.String] = []

  /// Optional. Indicates whether the cache volume has global file lock enabled.
  public var enableGlobalFileLock: Swift.Bool? = nil

  /// Optional. Configuration of the cache volume.
  public var cacheConfig: CacheConfig? = nil

  /// Output only. State of the cache volume indicating the peering status.
  public var cacheState: CacheParameters.CacheState = CacheParameters.CacheState()

  /// Output only. Copy-paste-able commands to be used on user's ONTAP to accept
  /// peering requests.
  public var command: Swift.String = Swift.String()

  /// Optional. Expiration time for the peering command to be executed on user's
  /// ONTAP.
  public var peeringCommandExpiryTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Temporary passphrase generated to accept cluster peering
  /// command.
  public var passphrase: Swift.String = Swift.String()

  /// Output only. Detailed description of the current cache state.
  public var stateDetails: Swift.String = Swift.String()

  /// Initialize a new instance of `CacheParameters`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CacheParameters().with { $0.peerVolumeName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// State of the cache volume indicating the peering status.
  public enum CacheState: Codable, Equatable, Sendable {
    /// Default unspecified state.
    case unspecified
    /// State indicating waiting for cluster peering to be established.
    case pendingClusterPeering
    /// State indicating waiting for SVM peering to be established.
    case pendingSvmPeering
    /// State indicating successful establishment of peering with origin
    /// volumes's ONTAP cluster.
    case peered
    /// Terminal state wherein peering with origin volume's ONTAP cluster
    /// has failed.
    case error
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .pendingClusterPeering: return 1
      case .pendingSvmPeering: return 2
      case .peered: return 3
      case .error: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CACHE_STATE_UNSPECIFIED"
      case .pendingClusterPeering: return "PENDING_CLUSTER_PEERING"
      case .pendingSvmPeering: return "PENDING_SVM_PEERING"
      case .peered: return "PEERED"
      case .error: return "ERROR"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:CacheState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CACHE_STATE_UNSPECIFIED": self = .unspecified
      case "PENDING_CLUSTER_PEERING": self = .pendingClusterPeering
      case "PENDING_SVM_PEERING": self = .pendingSvmPeering
      case "PEERED": self = .peered
      case "ERROR": self = .error
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:CacheState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .pendingClusterPeering
      case 2: self = .pendingSvmPeering
      case 3: self = .peered
      case 4: self = .error
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .pendingClusterPeering: return try container.encode(1)
      case .pendingSvmPeering: return try container.encode(2)
      case .peered: return try container.encode(3)
      case .error: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.netapp.v1.CacheParameters"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
