// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Pre-populate cache volume with data from the origin volume.
public struct CachePrePopulate: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. List of directory-paths to be pre-populated for the FlexCache
  /// volume.
  public var pathList: [Swift.String] = []

  /// Optional. List of directory-paths to be excluded for pre-population for the
  /// FlexCache volume.
  public var excludePathList: [Swift.String] = []

  /// Optional. Flag indicating whether the directories listed with the
  /// `path_list` need to be recursively pre-populated.
  public var recursion: Swift.Bool? = nil

  /// Initialize a new instance of `CachePrePopulate`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CachePrePopulate().with { $0.pathList = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.netapp.v1.CachePrePopulate"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
