// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Configuration of the cache volume.
public struct CacheConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. Pre-populate cache volume with data from the origin volume.
  public var cachePrePopulate: CachePrePopulate? = nil

  /// Optional. Flag indicating whether writeback is enabled for the FlexCache
  /// volume.
  public var writebackEnabled: Swift.Bool? = nil

  /// Optional. Flag indicating whether a CIFS change notification is enabled for
  /// the FlexCache volume.
  public var cifsChangeNotifyEnabled: Swift.Bool? = nil

  /// Output only. State of the prepopulation job indicating how the
  /// prepopulation is progressing.
  public var cachePrePopulateState: CacheConfig.CachePrePopulateState =
    CacheConfig.CachePrePopulateState()

  /// Initialize a new instance of `CacheConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CacheConfig().with { $0.cachePrePopulate = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// State of the prepopulation job indicating how the prepopulation is
  /// progressing.
  public enum CachePrePopulateState: Codable, Equatable, Sendable {
    /// Default unspecified state.
    case unspecified
    /// State representing when the most recent create or update request did not
    /// require a prepopulation job.
    case notNeeded
    /// State representing when the most recent update request requested a
    /// prepopulation job but it has not yet completed.
    case inProgress
    /// State representing when the most recent update request requested a
    /// prepopulation job and it has completed successfully.
    case complete
    /// State representing when the most recent update request requested a
    /// prepopulation job but the prepopulate job failed.
    case error
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .notNeeded: return 1
      case .inProgress: return 2
      case .complete: return 3
      case .error: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CACHE_PRE_POPULATE_STATE_UNSPECIFIED"
      case .notNeeded: return "NOT_NEEDED"
      case .inProgress: return "IN_PROGRESS"
      case .complete: return "COMPLETE"
      case .error: return "ERROR"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:CachePrePopulateState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CACHE_PRE_POPULATE_STATE_UNSPECIFIED": self = .unspecified
      case "NOT_NEEDED": self = .notNeeded
      case "IN_PROGRESS": self = .inProgress
      case "COMPLETE": self = .complete
      case "ERROR": self = .error
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:CachePrePopulateState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .notNeeded
      case 2: self = .inProgress
      case 3: self = .complete
      case 4: self = .error
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .notNeeded: return try container.encode(1)
      case .inProgress: return try container.encode(2)
      case .complete: return try container.encode(3)
      case .error: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.netapp.v1.CacheConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
