// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// CreateBackupVaultRequest creates a backup vault.
public struct CreateBackupVaultRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The location to create the backup vaults, in the format
  /// `projects/{project_id}/locations/{location}`
  public var parent: Swift.String = Swift.String()

  /// Required. The ID to use for the backupVault.
  /// The ID must be unique within the specified location.
  /// Must contain only letters, numbers and hyphen, with the first
  /// character a letter, the last a letter or a
  /// number, and a 63 character maximum.
  public var backupVaultId: Swift.String = Swift.String()

  /// Required. A backupVault resource
  public var backupVault: BackupVault? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CreateBackupVaultRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateBackupVaultRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let backupVaultId = CodingKeys(stringValue: "backupVaultId")
    static let backupVault = CodingKeys(stringValue: "backupVault")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "backupVaultId",
      "backupVault",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .backupVaultId) {
      self.backupVaultId = value
    }
    self.backupVault = try container.decodeIfPresent(BackupVault.self, forKey: .backupVault)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.backupVaultId, forKey: .backupVaultId)
    try container.encodeIfPresent(self.backupVault, forKey: .backupVault)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.netapp.v1.CreateBackupVaultRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
