// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// DestinationVolumeParameters specify input parameters used for creating
/// destination volume.
public struct DestinationVolumeParameters: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Existing destination StoragePool name.
  public var storagePool: Swift.String = Swift.String()

  /// Desired destination volume resource id. If not specified, source volume's
  /// resource id will be used.
  /// This value must start with a lowercase letter followed by up to 62
  /// lowercase letters, numbers, or hyphens, and cannot end with a hyphen.
  public var volumeId: Swift.String = Swift.String()

  /// Destination volume's share name. If not specified, source volume's share
  /// name will be used.
  public var shareName: Swift.String = Swift.String()

  /// Description for the destination volume.
  public var description: Swift.String? = nil

  /// Optional. Tiering policy for the volume.
  public var tieringPolicy: TieringPolicy? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DestinationVolumeParameters`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DestinationVolumeParameters().with { $0.storagePool = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let storagePool = CodingKeys(stringValue: "storagePool")
    static let volumeId = CodingKeys(stringValue: "volumeId")
    static let shareName = CodingKeys(stringValue: "shareName")
    static let description = CodingKeys(stringValue: "description")
    static let tieringPolicy = CodingKeys(stringValue: "tieringPolicy")

    static let _knownKeys: Set<Swift.String> = [
      "storagePool",
      "volumeId",
      "shareName",
      "description",
      "tieringPolicy",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .storagePool) {
      self.storagePool = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .volumeId) {
      self.volumeId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .shareName) {
      self.shareName = value
    }
    self.description = try container.decodeIfPresent(Swift.String.self, forKey: .description)
    self.tieringPolicy = try container.decodeIfPresent(TieringPolicy.self, forKey: .tieringPolicy)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.storagePool, forKey: .storagePool)
    try container.encode(self.volumeId, forKey: .volumeId)
    try container.encode(self.shareName, forKey: .shareName)
    try container.encodeIfPresent(self.description, forKey: .description)
    try container.encodeIfPresent(self.tieringPolicy, forKey: .tieringPolicy)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.netapp.v1.DestinationVolumeParameters"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
