// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// EstablishPeeringRequest establishes cluster and svm peerings between the
/// source and the destination replications.
public struct EstablishPeeringRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name of the replication, in the format of
  /// projects/{project_id}/locations/{location}/volumes/{volume_id}/replications/{replication_id}.
  public var name: Swift.String = Swift.String()

  /// Required. Name of the user's local source cluster to be peered with the
  /// destination cluster.
  public var peerClusterName: Swift.String = Swift.String()

  /// Required. Name of the user's local source vserver svm to be peered with the
  /// destination vserver svm.
  public var peerSvmName: Swift.String = Swift.String()

  /// Optional. List of IPv4 ip addresses to be used for peering.
  public var peerIpAddresses: [Swift.String] = []

  /// Required. Name of the user's local source volume to be peered with the
  /// destination volume.
  public var peerVolumeName: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `EstablishPeeringRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EstablishPeeringRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let peerClusterName = CodingKeys(stringValue: "peerClusterName")
    static let peerSvmName = CodingKeys(stringValue: "peerSvmName")
    static let peerIpAddresses = CodingKeys(stringValue: "peerIpAddresses")
    static let peerVolumeName = CodingKeys(stringValue: "peerVolumeName")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "peerClusterName",
      "peerSvmName",
      "peerIpAddresses",
      "peerVolumeName",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .peerClusterName) {
      self.peerClusterName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .peerSvmName) {
      self.peerSvmName = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .peerIpAddresses) {
      self.peerIpAddresses = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .peerVolumeName) {
      self.peerVolumeName = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.peerClusterName, forKey: .peerClusterName)
    try container.encode(self.peerSvmName, forKey: .peerSvmName)
    try container.encode(self.peerIpAddresses, forKey: .peerIpAddresses)
    try container.encode(self.peerVolumeName, forKey: .peerVolumeName)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.netapp.v1.EstablishPeeringRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
