// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The Hybrid Replication parameters for the volume.
public struct HybridReplicationParameters: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Desired name for the replication of this volume.
  public var replication: Swift.String = Swift.String()

  /// Required. Name of the user's local source volume to be peered with the
  /// destination volume.
  public var peerVolumeName: Swift.String = Swift.String()

  /// Required. Name of the user's local source cluster to be peered with the
  /// destination cluster.
  public var peerClusterName: Swift.String = Swift.String()

  /// Required. Name of the user's local source vserver svm to be peered with the
  /// destination vserver svm.
  public var peerSvmName: Swift.String = Swift.String()

  /// Required. List of node ip addresses to be peered with.
  public var peerIpAddresses: [Swift.String] = []

  /// Optional. Name of source cluster location associated with the Hybrid
  /// replication. This is a free-form field for the display purpose only.
  public var clusterLocation: Swift.String = Swift.String()

  /// Optional. Description of the replication.
  public var description: Swift.String = Swift.String()

  /// Optional. Labels to be added to the replication as the key value pairs.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. Replication Schedule for the replication created.
  public var replicationSchedule: HybridReplicationSchedule = HybridReplicationSchedule()

  /// Optional. Type of the hybrid replication.
  public var hybridReplicationType: HybridReplicationParameters.VolumeHybridReplicationType =
    HybridReplicationParameters.VolumeHybridReplicationType()

  /// Optional. Constituent volume count for large volume.
  public var largeVolumeConstituentCount: Swift.Int32 = Swift.Int32()

  /// Initialize a new instance of `HybridReplicationParameters`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = HybridReplicationParameters().with { $0.replication = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Type of the volume's hybrid replication.
  public enum VolumeHybridReplicationType: Codable, Equatable, Sendable {
    /// Unspecified hybrid replication type.
    case unspecified
    /// Hybrid replication type for migration.
    case migration
    /// Hybrid replication type for continuous replication.
    case continuousReplication
    /// New field for reversible OnPrem replication, to be used for data
    /// protection.
    case onpremReplication
    /// New field for reversible OnPrem replication, to be used for data
    /// protection.
    case reverseOnpremReplication
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .migration: return 1
      case .continuousReplication: return 2
      case .onpremReplication: return 3
      case .reverseOnpremReplication: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "VOLUME_HYBRID_REPLICATION_TYPE_UNSPECIFIED"
      case .migration: return "MIGRATION"
      case .continuousReplication: return "CONTINUOUS_REPLICATION"
      case .onpremReplication: return "ONPREM_REPLICATION"
      case .reverseOnpremReplication: return "REVERSE_ONPREM_REPLICATION"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:VolumeHybridReplicationType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "VOLUME_HYBRID_REPLICATION_TYPE_UNSPECIFIED": self = .unspecified
      case "MIGRATION": self = .migration
      case "CONTINUOUS_REPLICATION": self = .continuousReplication
      case "ONPREM_REPLICATION": self = .onpremReplication
      case "REVERSE_ONPREM_REPLICATION": self = .reverseOnpremReplication
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:VolumeHybridReplicationType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .migration
      case 2: self = .continuousReplication
      case 3: self = .onpremReplication
      case 4: self = .reverseOnpremReplication
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .migration: return try container.encode(1)
      case .continuousReplication: return try container.encode(2)
      case .onpremReplication: return try container.encode(3)
      case .reverseOnpremReplication: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.netapp.v1.HybridReplicationParameters"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
