// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// HybridPeeringDetails contains details about the hybrid peering.
public struct HybridPeeringDetails: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. IP address of the subnet.
  public var subnetIp: Swift.String = Swift.String()

  /// Output only. Copy-paste-able commands to be used on user's ONTAP to accept
  /// peering requests.
  public var command: Swift.String = Swift.String()

  /// Output only. Expiration time for the peering command to be executed on
  /// user's ONTAP.
  public var commandExpiryTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. Temporary passphrase generated to accept cluster peering
  /// command.
  public var passphrase: Swift.String = Swift.String()

  /// Output only. Name of the user's local source volume to be peered with the
  /// destination volume.
  public var peerVolumeName: Swift.String = Swift.String()

  /// Output only. Name of the user's local source cluster to be peered with the
  /// destination cluster.
  public var peerClusterName: Swift.String = Swift.String()

  /// Output only. Name of the user's local source vserver svm to be peered with
  /// the destination vserver svm.
  public var peerSvmName: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `HybridPeeringDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = HybridPeeringDetails().with { $0.subnetIp = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let subnetIp = CodingKeys(stringValue: "subnetIp")
    static let command = CodingKeys(stringValue: "command")
    static let commandExpiryTime = CodingKeys(stringValue: "commandExpiryTime")
    static let passphrase = CodingKeys(stringValue: "passphrase")
    static let peerVolumeName = CodingKeys(stringValue: "peerVolumeName")
    static let peerClusterName = CodingKeys(stringValue: "peerClusterName")
    static let peerSvmName = CodingKeys(stringValue: "peerSvmName")

    static let _knownKeys: Set<Swift.String> = [
      "subnetIp",
      "command",
      "commandExpiryTime",
      "passphrase",
      "peerVolumeName",
      "peerClusterName",
      "peerSvmName",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .subnetIp) {
      self.subnetIp = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .command) {
      self.command = value
    }
    self.commandExpiryTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .commandExpiryTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .passphrase) {
      self.passphrase = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .peerVolumeName) {
      self.peerVolumeName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .peerClusterName) {
      self.peerClusterName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .peerSvmName) {
      self.peerSvmName = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.subnetIp, forKey: .subnetIp)
    try container.encode(self.command, forKey: .command)
    try container.encodeIfPresent(self.commandExpiryTime, forKey: .commandExpiryTime)
    try container.encode(self.passphrase, forKey: .passphrase)
    try container.encode(self.peerVolumeName, forKey: .peerVolumeName)
    try container.encode(self.peerClusterName, forKey: .peerClusterName)
    try container.encode(self.peerSvmName, forKey: .peerSvmName)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.netapp.v1.HybridPeeringDetails"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
