// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// ListBackupsRequest lists backups.
public struct ListBackupsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The backupVault for which to retrieve backup information,
  /// in the format
  /// `projects/{project_id}/locations/{location}/backupVaults/{backup_vault_id}`.
  /// To retrieve backup information for all locations, use "-" for the
  /// `{location}` value.
  /// To retrieve backup information for all backupVaults, use "-" for the
  /// `{backup_vault_id}` value.
  /// To retrieve backup information for a volume, use "-" for the
  /// `{backup_vault_id}` value and specify volume full name with the filter.
  public var parent: Swift.String = Swift.String()

  /// The maximum number of items to return. The service may return fewer
  /// than this value. The maximum value
  /// is 1000; values above 1000 will be coerced to 1000.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// The next_page_token value to use if there are additional
  /// results to retrieve for this list request.
  public var pageToken: Swift.String = Swift.String()

  /// Sort results. Supported values are "name", "name desc" or "" (unsorted).
  public var orderBy: Swift.String = Swift.String()

  /// The standard list filter.
  /// If specified, backups will be returned based on the attribute name that
  /// matches the filter expression. If empty, then no backups are filtered out.
  /// See https://google.aip.dev/160
  public var filter: Swift.String = Swift.String()

  /// Initialize a new instance of `ListBackupsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListBackupsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.netapp.v1.ListBackupsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
