// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Metadata for a given
/// [google.cloud.location.Location][google.cloud.location.Location].
///
/// [google.cloud.location.Location]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.Location
public struct LocationMetadata: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Supported service levels in a location.
  public var supportedServiceLevels: [ServiceLevel] = []

  /// Output only. Supported flex performance in a location.
  public var supportedFlexPerformance: [FlexPerformance] = []

  /// Output only. Indicates if the location has VCP support.
  public var hasVcp: Swift.Bool = Swift.Bool()

  /// Output only. Indicates if the location has ONTAP Proxy support.
  public var hasOntapProxy: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `LocationMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LocationMetadata().with { $0.supportedServiceLevels = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let supportedServiceLevels = CodingKeys(stringValue: "supportedServiceLevels")
    static let supportedFlexPerformance = CodingKeys(stringValue: "supportedFlexPerformance")
    static let hasVcp = CodingKeys(stringValue: "hasVcp")
    static let hasOntapProxy = CodingKeys(stringValue: "hasOntapProxy")

    static let _knownKeys: Set<Swift.String> = [
      "supportedServiceLevels",
      "supportedFlexPerformance",
      "hasVcp",
      "hasOntapProxy",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [ServiceLevel].self, forKey: .supportedServiceLevels)
    {
      self.supportedServiceLevels = value
    }
    if let value = try container.decodeIfPresent(
      [FlexPerformance].self, forKey: .supportedFlexPerformance)
    {
      self.supportedFlexPerformance = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .hasVcp) {
      self.hasVcp = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .hasOntapProxy) {
      self.hasOntapProxy = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.supportedServiceLevels, forKey: .supportedServiceLevels)
    try container.encode(self.supportedFlexPerformance, forKey: .supportedFlexPerformance)
    try container.encode(self.hasVcp, forKey: .hasVcp)
    try container.encode(self.hasOntapProxy, forKey: .hasOntapProxy)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.netapp.v1.LocationMetadata"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
