// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Make a snapshot once a month e.g. at 2nd 04:00, 7th 05:20, 24th 23:50
public struct MonthlySchedule: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The maximum number of Snapshots to keep for the hourly schedule
  public var snapshotsToKeep: Swift.Double? = nil

  /// Set the minute of the hour to start the snapshot (0-59), defaults to the
  /// top of the hour (0).
  public var minute: Swift.Double? = nil

  /// Set the hour to start the snapshot (0-23), defaults to midnight (0).
  public var hour: Swift.Double? = nil

  /// Set the day or days of the month to make a snapshot (1-31). Accepts a
  /// comma separated number of days. Defaults to '1'.
  public var daysOfMonth: Swift.String? = nil

  /// Initialize a new instance of `MonthlySchedule`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MonthlySchedule().with { $0.snapshotsToKeep = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.netapp.v1.MonthlySchedule"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
