// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Make a snapshot once a month e.g. at 2nd 04:00, 7th 05:20, 24th 23:50
public struct MonthlySchedule: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The maximum number of Snapshots to keep for the hourly schedule
  public var snapshotsToKeep: Swift.Double? = nil

  /// Set the minute of the hour to start the snapshot (0-59), defaults to the
  /// top of the hour (0).
  public var minute: Swift.Double? = nil

  /// Set the hour to start the snapshot (0-23), defaults to midnight (0).
  public var hour: Swift.Double? = nil

  /// Set the day or days of the month to make a snapshot (1-31). Accepts a
  /// comma separated number of days. Defaults to '1'.
  public var daysOfMonth: Swift.String? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `MonthlySchedule`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MonthlySchedule().with { $0.snapshotsToKeep = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let snapshotsToKeep = CodingKeys(stringValue: "snapshotsToKeep")
    static let minute = CodingKeys(stringValue: "minute")
    static let hour = CodingKeys(stringValue: "hour")
    static let daysOfMonth = CodingKeys(stringValue: "daysOfMonth")

    static let _knownKeys: Set<Swift.String> = [
      "snapshotsToKeep",
      "minute",
      "hour",
      "daysOfMonth",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.snapshotsToKeep = try container.decodeIfPresent(
      Swift.Double.self, forKey: .snapshotsToKeep)
    self.minute = try container.decodeIfPresent(Swift.Double.self, forKey: .minute)
    self.hour = try container.decodeIfPresent(Swift.Double.self, forKey: .hour)
    self.daysOfMonth = try container.decodeIfPresent(Swift.String.self, forKey: .daysOfMonth)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.snapshotsToKeep, forKey: .snapshotsToKeep)
    try container.encodeIfPresent(self.minute, forKey: .minute)
    try container.encodeIfPresent(self.hour, forKey: .hour)
    try container.encodeIfPresent(self.daysOfMonth, forKey: .daysOfMonth)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.netapp.v1.MonthlySchedule"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
