// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// View only mount options for a volume.
public struct MountOption: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Export string
  public var export: Swift.String = Swift.String()

  /// Full export string
  public var exportFull: Swift.String = Swift.String()

  /// Protocol to mount with.
  public var `protocol`: Protocols = Protocols()

  /// Instructions for mounting
  public var instructions: Swift.String = Swift.String()

  /// Output only. IP Address.
  public var ipAddress: Swift.String = Swift.String()

  /// Initialize a new instance of `MountOption`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MountOption().with { $0.export = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case export = "export"
    case exportFull = "exportFull"
    case `protocol` = "protocol"
    case instructions = "instructions"
    case ipAddress = "ipAddress"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.export = try container.decode(Swift.String.self, forKey: .export)
    self.exportFull = try container.decode(Swift.String.self, forKey: .exportFull)
    self.`protocol` = try container.decode(Protocols.self, forKey: .`protocol`)
    self.instructions = try container.decode(Swift.String.self, forKey: .instructions)
    self.ipAddress = try container.decode(Swift.String.self, forKey: .ipAddress)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.export, forKey: .export)
    try container.encode(self.exportFull, forKey: .exportFull)
    try container.encode(self.`protocol`, forKey: .`protocol`)
    try container.encode(self.instructions, forKey: .instructions)
    try container.encode(self.ipAddress, forKey: .ipAddress)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.netapp.v1.MountOption"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
