// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class NetAppRetry: NetAppStub {
    let inner: any NetAppStub
    let options: GoogleGax.ClientOptions

    public init(_ inner: any NetAppStub, options: GoogleGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func listStoragePools(
      request: ListStoragePoolsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.ListStoragePoolsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListStoragePoolsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetAppV1.ListStoragePoolsResponse
          in
          return try await self.inner.listStoragePools(request: r, options: o)
        })
    }

    public func createStoragePool(
      request: CreateStoragePoolRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateStoragePoolRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createStoragePool(request: r, options: o)
        })
    }

    public func getStoragePool(
      request: GetStoragePoolRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.StoragePool {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetStoragePoolRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetAppV1.StoragePool
          in
          return try await self.inner.getStoragePool(request: r, options: o)
        })
    }

    public func updateStoragePool(
      request: UpdateStoragePoolRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateStoragePoolRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateStoragePool(request: r, options: o)
        })
    }

    public func deleteStoragePool(
      request: DeleteStoragePoolRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteStoragePoolRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteStoragePool(request: r, options: o)
        })
    }

    public func validateDirectoryService(
      request: ValidateDirectoryServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ValidateDirectoryServiceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.validateDirectoryService(request: r, options: o)
        })
    }

    public func switchActiveReplicaZone(
      request: SwitchActiveReplicaZoneRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: SwitchActiveReplicaZoneRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.switchActiveReplicaZone(request: r, options: o)
        })
    }

    public func listVolumes(
      request: ListVolumesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.ListVolumesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListVolumesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetAppV1.ListVolumesResponse
          in
          return try await self.inner.listVolumes(request: r, options: o)
        })
    }

    public func getVolume(
      request: GetVolumeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.Volume {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetVolumeRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetAppV1.Volume
          in
          return try await self.inner.getVolume(request: r, options: o)
        })
    }

    public func createVolume(
      request: CreateVolumeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateVolumeRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createVolume(request: r, options: o)
        })
    }

    public func updateVolume(
      request: UpdateVolumeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateVolumeRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateVolume(request: r, options: o)
        })
    }

    public func deleteVolume(
      request: DeleteVolumeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteVolumeRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteVolume(request: r, options: o)
        })
    }

    public func revertVolume(
      request: RevertVolumeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: RevertVolumeRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.revertVolume(request: r, options: o)
        })
    }

    public func establishVolumePeering(
      request: EstablishVolumePeeringRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: EstablishVolumePeeringRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.establishVolumePeering(request: r, options: o)
        })
    }

    public func listSnapshots(
      request: ListSnapshotsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.ListSnapshotsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListSnapshotsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetAppV1.ListSnapshotsResponse
          in
          return try await self.inner.listSnapshots(request: r, options: o)
        })
    }

    public func getSnapshot(
      request: GetSnapshotRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.Snapshot {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetSnapshotRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetAppV1.Snapshot
          in
          return try await self.inner.getSnapshot(request: r, options: o)
        })
    }

    public func createSnapshot(
      request: CreateSnapshotRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateSnapshotRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createSnapshot(request: r, options: o)
        })
    }

    public func deleteSnapshot(
      request: DeleteSnapshotRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteSnapshotRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteSnapshot(request: r, options: o)
        })
    }

    public func updateSnapshot(
      request: UpdateSnapshotRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateSnapshotRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateSnapshot(request: r, options: o)
        })
    }

    public func listActiveDirectories(
      request: ListActiveDirectoriesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.ListActiveDirectoriesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListActiveDirectoriesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetAppV1.ListActiveDirectoriesResponse
          in
          return try await self.inner.listActiveDirectories(request: r, options: o)
        })
    }

    public func getActiveDirectory(
      request: GetActiveDirectoryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.ActiveDirectory {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetActiveDirectoryRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetAppV1.ActiveDirectory
          in
          return try await self.inner.getActiveDirectory(request: r, options: o)
        })
    }

    public func createActiveDirectory(
      request: CreateActiveDirectoryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateActiveDirectoryRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createActiveDirectory(request: r, options: o)
        })
    }

    public func updateActiveDirectory(
      request: UpdateActiveDirectoryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateActiveDirectoryRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateActiveDirectory(request: r, options: o)
        })
    }

    public func deleteActiveDirectory(
      request: DeleteActiveDirectoryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteActiveDirectoryRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteActiveDirectory(request: r, options: o)
        })
    }

    public func listKmsConfigs(
      request: ListKmsConfigsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.ListKmsConfigsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListKmsConfigsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetAppV1.ListKmsConfigsResponse
          in
          return try await self.inner.listKmsConfigs(request: r, options: o)
        })
    }

    public func createKmsConfig(
      request: CreateKmsConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateKmsConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createKmsConfig(request: r, options: o)
        })
    }

    public func getKmsConfig(
      request: GetKmsConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.KmsConfig {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetKmsConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetAppV1.KmsConfig
          in
          return try await self.inner.getKmsConfig(request: r, options: o)
        })
    }

    public func updateKmsConfig(
      request: UpdateKmsConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateKmsConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateKmsConfig(request: r, options: o)
        })
    }

    public func encryptVolumes(
      request: EncryptVolumesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: EncryptVolumesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.encryptVolumes(request: r, options: o)
        })
    }

    public func verifyKmsConfig(
      request: VerifyKmsConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.VerifyKmsConfigResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: VerifyKmsConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetAppV1.VerifyKmsConfigResponse
          in
          return try await self.inner.verifyKmsConfig(request: r, options: o)
        })
    }

    public func deleteKmsConfig(
      request: DeleteKmsConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteKmsConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteKmsConfig(request: r, options: o)
        })
    }

    public func listReplications(
      request: ListReplicationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.ListReplicationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListReplicationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetAppV1.ListReplicationsResponse
          in
          return try await self.inner.listReplications(request: r, options: o)
        })
    }

    public func getReplication(
      request: GetReplicationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.Replication {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetReplicationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetAppV1.Replication
          in
          return try await self.inner.getReplication(request: r, options: o)
        })
    }

    public func createReplication(
      request: CreateReplicationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateReplicationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createReplication(request: r, options: o)
        })
    }

    public func deleteReplication(
      request: DeleteReplicationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteReplicationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteReplication(request: r, options: o)
        })
    }

    public func updateReplication(
      request: UpdateReplicationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateReplicationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateReplication(request: r, options: o)
        })
    }

    public func stopReplication(
      request: StopReplicationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: StopReplicationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.stopReplication(request: r, options: o)
        })
    }

    public func resumeReplication(
      request: ResumeReplicationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ResumeReplicationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.resumeReplication(request: r, options: o)
        })
    }

    public func reverseReplicationDirection(
      request: ReverseReplicationDirectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ReverseReplicationDirectionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.reverseReplicationDirection(request: r, options: o)
        })
    }

    public func establishPeering(
      request: EstablishPeeringRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: EstablishPeeringRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.establishPeering(request: r, options: o)
        })
    }

    public func syncReplication(
      request: SyncReplicationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: SyncReplicationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.syncReplication(request: r, options: o)
        })
    }

    public func createBackupVault(
      request: CreateBackupVaultRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateBackupVaultRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createBackupVault(request: r, options: o)
        })
    }

    public func getBackupVault(
      request: GetBackupVaultRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.BackupVault {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetBackupVaultRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetAppV1.BackupVault
          in
          return try await self.inner.getBackupVault(request: r, options: o)
        })
    }

    public func listBackupVaults(
      request: ListBackupVaultsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.ListBackupVaultsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListBackupVaultsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetAppV1.ListBackupVaultsResponse
          in
          return try await self.inner.listBackupVaults(request: r, options: o)
        })
    }

    public func updateBackupVault(
      request: UpdateBackupVaultRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateBackupVaultRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateBackupVault(request: r, options: o)
        })
    }

    public func deleteBackupVault(
      request: DeleteBackupVaultRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteBackupVaultRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteBackupVault(request: r, options: o)
        })
    }

    public func createBackup(
      request: CreateBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateBackupRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createBackup(request: r, options: o)
        })
    }

    public func getBackup(
      request: GetBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.Backup {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetBackupRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetAppV1.Backup
          in
          return try await self.inner.getBackup(request: r, options: o)
        })
    }

    public func listBackups(
      request: ListBackupsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.ListBackupsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListBackupsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetAppV1.ListBackupsResponse
          in
          return try await self.inner.listBackups(request: r, options: o)
        })
    }

    public func deleteBackup(
      request: DeleteBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteBackupRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteBackup(request: r, options: o)
        })
    }

    public func updateBackup(
      request: UpdateBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateBackupRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateBackup(request: r, options: o)
        })
    }

    public func createBackupPolicy(
      request: CreateBackupPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateBackupPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createBackupPolicy(request: r, options: o)
        })
    }

    public func getBackupPolicy(
      request: GetBackupPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.BackupPolicy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetBackupPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetAppV1.BackupPolicy
          in
          return try await self.inner.getBackupPolicy(request: r, options: o)
        })
    }

    public func listBackupPolicies(
      request: ListBackupPoliciesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.ListBackupPoliciesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListBackupPoliciesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetAppV1.ListBackupPoliciesResponse
          in
          return try await self.inner.listBackupPolicies(request: r, options: o)
        })
    }

    public func updateBackupPolicy(
      request: UpdateBackupPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateBackupPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateBackupPolicy(request: r, options: o)
        })
    }

    public func deleteBackupPolicy(
      request: DeleteBackupPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteBackupPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteBackupPolicy(request: r, options: o)
        })
    }

    public func listQuotaRules(
      request: ListQuotaRulesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.ListQuotaRulesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListQuotaRulesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetAppV1.ListQuotaRulesResponse
          in
          return try await self.inner.listQuotaRules(request: r, options: o)
        })
    }

    public func getQuotaRule(
      request: GetQuotaRuleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.QuotaRule {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetQuotaRuleRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetAppV1.QuotaRule
          in
          return try await self.inner.getQuotaRule(request: r, options: o)
        })
    }

    public func createQuotaRule(
      request: CreateQuotaRuleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateQuotaRuleRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createQuotaRule(request: r, options: o)
        })
    }

    public func updateQuotaRule(
      request: UpdateQuotaRuleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateQuotaRuleRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateQuotaRule(request: r, options: o)
        })
    }

    public func deleteQuotaRule(
      request: DeleteQuotaRuleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteQuotaRuleRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteQuotaRule(request: r, options: o)
        })
    }

    public func restoreBackupFiles(
      request: RestoreBackupFilesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: RestoreBackupFilesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.restoreBackupFiles(request: r, options: o)
        })
    }

    public func listHostGroups(
      request: ListHostGroupsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.ListHostGroupsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListHostGroupsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetAppV1.ListHostGroupsResponse
          in
          return try await self.inner.listHostGroups(request: r, options: o)
        })
    }

    public func getHostGroup(
      request: GetHostGroupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.HostGroup {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetHostGroupRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetAppV1.HostGroup
          in
          return try await self.inner.getHostGroup(request: r, options: o)
        })
    }

    public func createHostGroup(
      request: CreateHostGroupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateHostGroupRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createHostGroup(request: r, options: o)
        })
    }

    public func updateHostGroup(
      request: UpdateHostGroupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateHostGroupRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateHostGroup(request: r, options: o)
        })
    }

    public func deleteHostGroup(
      request: DeleteHostGroupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteHostGroupRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteHostGroup(request: r, options: o)
        })
    }

    public func executeOntapPost(
      request: ExecuteOntapPostRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.ExecuteOntapPostResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ExecuteOntapPostRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetAppV1.ExecuteOntapPostResponse
          in
          return try await self.inner.executeOntapPost(request: r, options: o)
        })
    }

    public func executeOntapGet(
      request: ExecuteOntapGetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.ExecuteOntapGetResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ExecuteOntapGetRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetAppV1.ExecuteOntapGetResponse
          in
          return try await self.inner.executeOntapGet(request: r, options: o)
        })
    }

    public func executeOntapDelete(
      request: ExecuteOntapDeleteRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.ExecuteOntapDeleteResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ExecuteOntapDeleteRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetAppV1.ExecuteOntapDeleteResponse
          in
          return try await self.inner.executeOntapDelete(request: r, options: o)
        })
    }

    public func executeOntapPatch(
      request: ExecuteOntapPatchRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.ExecuteOntapPatchResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ExecuteOntapPatchRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetAppV1.ExecuteOntapPatchResponse
          in
          return try await self.inner.executeOntapPatch(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
