// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleCloudWKT
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  protocol NetAppStub: Sendable {
    func listStoragePools(
      request: ListStoragePoolsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.ListStoragePoolsResponse

    func createStoragePool(
      request: CreateStoragePoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getStoragePool(
      request: GetStoragePoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.StoragePool

    func updateStoragePool(
      request: UpdateStoragePoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteStoragePool(
      request: DeleteStoragePoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func validateDirectoryService(
      request: ValidateDirectoryServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func switchActiveReplicaZone(
      request: SwitchActiveReplicaZoneRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listVolumes(
      request: ListVolumesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.ListVolumesResponse

    func getVolume(
      request: GetVolumeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.Volume

    func createVolume(
      request: CreateVolumeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateVolume(
      request: UpdateVolumeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteVolume(
      request: DeleteVolumeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func revertVolume(
      request: RevertVolumeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func establishVolumePeering(
      request: EstablishVolumePeeringRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listSnapshots(
      request: ListSnapshotsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.ListSnapshotsResponse

    func getSnapshot(
      request: GetSnapshotRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.Snapshot

    func createSnapshot(
      request: CreateSnapshotRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteSnapshot(
      request: DeleteSnapshotRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateSnapshot(
      request: UpdateSnapshotRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listActiveDirectories(
      request: ListActiveDirectoriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.ListActiveDirectoriesResponse

    func getActiveDirectory(
      request: GetActiveDirectoryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.ActiveDirectory

    func createActiveDirectory(
      request: CreateActiveDirectoryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateActiveDirectory(
      request: UpdateActiveDirectoryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteActiveDirectory(
      request: DeleteActiveDirectoryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listKmsConfigs(
      request: ListKmsConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.ListKmsConfigsResponse

    func createKmsConfig(
      request: CreateKmsConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getKmsConfig(
      request: GetKmsConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.KmsConfig

    func updateKmsConfig(
      request: UpdateKmsConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func encryptVolumes(
      request: EncryptVolumesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func verifyKmsConfig(
      request: VerifyKmsConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.VerifyKmsConfigResponse

    func deleteKmsConfig(
      request: DeleteKmsConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listReplications(
      request: ListReplicationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.ListReplicationsResponse

    func getReplication(
      request: GetReplicationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.Replication

    func createReplication(
      request: CreateReplicationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteReplication(
      request: DeleteReplicationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateReplication(
      request: UpdateReplicationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func stopReplication(
      request: StopReplicationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func resumeReplication(
      request: ResumeReplicationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func reverseReplicationDirection(
      request: ReverseReplicationDirectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func establishPeering(
      request: EstablishPeeringRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func syncReplication(
      request: SyncReplicationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func createBackupVault(
      request: CreateBackupVaultRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getBackupVault(
      request: GetBackupVaultRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.BackupVault

    func listBackupVaults(
      request: ListBackupVaultsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.ListBackupVaultsResponse

    func updateBackupVault(
      request: UpdateBackupVaultRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteBackupVault(
      request: DeleteBackupVaultRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func createBackup(
      request: CreateBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getBackup(
      request: GetBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.Backup

    func listBackups(
      request: ListBackupsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.ListBackupsResponse

    func deleteBackup(
      request: DeleteBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateBackup(
      request: UpdateBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func createBackupPolicy(
      request: CreateBackupPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getBackupPolicy(
      request: GetBackupPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.BackupPolicy

    func listBackupPolicies(
      request: ListBackupPoliciesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.ListBackupPoliciesResponse

    func updateBackupPolicy(
      request: UpdateBackupPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteBackupPolicy(
      request: DeleteBackupPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listQuotaRules(
      request: ListQuotaRulesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.ListQuotaRulesResponse

    func getQuotaRule(
      request: GetQuotaRuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.QuotaRule

    func createQuotaRule(
      request: CreateQuotaRuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateQuotaRule(
      request: UpdateQuotaRuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteQuotaRule(
      request: DeleteQuotaRuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func restoreBackupFiles(
      request: RestoreBackupFilesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listHostGroups(
      request: ListHostGroupsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.ListHostGroupsResponse

    func getHostGroup(
      request: GetHostGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.HostGroup

    func createHostGroup(
      request: CreateHostGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateHostGroup(
      request: UpdateHostGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteHostGroup(
      request: DeleteHostGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func executeOntapPost(
      request: ExecuteOntapPostRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.ExecuteOntapPostResponse

    func executeOntapGet(
      request: ExecuteOntapGetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.ExecuteOntapGetResponse

    func executeOntapDelete(
      request: ExecuteOntapDeleteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.ExecuteOntapDeleteResponse

    func executeOntapPatch(
      request: ExecuteOntapPatchRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetAppV1.ExecuteOntapPatchResponse

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}
