// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Replication is a nested resource under Volume, that describes a
/// cross-region replication relationship between 2 volumes in different
/// regions.
public struct Replication: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. The resource name of the Replication.
  /// Format:
  /// `projects/{project_id}/locations/{location}/volumes/{volume_id}/replications/{replication_id}`.
  public var name: Swift.String = Swift.String()

  /// Output only. State of the replication.
  public var state: Replication.State = Replication.State()

  /// Output only. State details of the replication.
  public var stateDetails: Swift.String = Swift.String()

  /// Output only. Indicates whether this points to source or destination.
  public var role: Replication.ReplicationRole = Replication.ReplicationRole()

  /// Required. Indicates the schedule for replication.
  public var replicationSchedule: Replication.ReplicationSchedule =
    Replication.ReplicationSchedule()

  /// Output only. Indicates the state of mirroring.
  public var mirrorState: Replication.MirrorState = Replication.MirrorState()

  /// Output only. Condition of the relationship. Can be one of the following:
  /// - true: The replication relationship is healthy. It has not missed the most
  /// recent scheduled transfer.
  /// - false: The replication relationship is not healthy. It has missed the
  /// most recent scheduled transfer.
  public var healthy: Swift.Bool? = nil

  /// Output only. Replication create time.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Full name of destination volume resource.
  /// Example : "projects/{project}/locations/{location}/volumes/{volume_id}"
  public var destinationVolume: Swift.String = Swift.String()

  /// Output only. Replication transfer statistics.
  public var transferStats: TransferStats? = nil

  /// Resource labels to represent user provided metadata.
  public var labels: [Swift.String: Swift.String] = [:]

  /// A description about this replication relationship.
  public var description: Swift.String? = nil

  /// Required. Input only. Destination volume parameters
  public var destinationVolumeParameters: DestinationVolumeParameters? = nil

  /// Output only. Full name of source volume resource.
  /// Example : "projects/{project}/locations/{location}/volumes/{volume_id}"
  public var sourceVolume: Swift.String = Swift.String()

  /// Output only. Hybrid peering details.
  public var hybridPeeringDetails: HybridPeeringDetails? = nil

  /// Optional. Location of the user cluster.
  public var clusterLocation: Swift.String = Swift.String()

  /// Output only. Type of the hybrid replication.
  public var hybridReplicationType: Replication.HybridReplicationType =
    Replication.HybridReplicationType()

  /// Output only. Copy pastable snapmirror commands to be executed on onprem
  /// cluster by the customer.
  public var hybridReplicationUserCommands: UserCommands? = nil

  /// Initialize a new instance of `Replication`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Replication().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The replication states
  /// New enum values may be added in future to indicate possible new states.
  public enum State: Codable, Equatable, Sendable {
    /// Unspecified replication State
    case unspecified
    /// Replication is creating.
    case creating
    /// Replication is ready.
    case ready
    /// Replication is updating.
    case updating
    /// Replication is deleting.
    case deleting
    /// Replication is in error state.
    case error
    /// Replication is waiting for cluster peering to be established.
    case pendingClusterPeering
    /// Replication is waiting for SVM peering to be established.
    case pendingSvmPeering
    /// Replication is waiting for Commands to be executed on Onprem ONTAP.
    case pendingRemoteResync
    /// Onprem ONTAP is destination and Replication can only be managed from
    /// Onprem.
    case externallyManagedReplication
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .ready: return 2
      case .updating: return 3
      case .deleting: return 5
      case .error: return 6
      case .pendingClusterPeering: return 8
      case .pendingSvmPeering: return 9
      case .pendingRemoteResync: return 10
      case .externallyManagedReplication: return 11
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .ready: return "READY"
      case .updating: return "UPDATING"
      case .deleting: return "DELETING"
      case .error: return "ERROR"
      case .pendingClusterPeering: return "PENDING_CLUSTER_PEERING"
      case .pendingSvmPeering: return "PENDING_SVM_PEERING"
      case .pendingRemoteResync: return "PENDING_REMOTE_RESYNC"
      case .externallyManagedReplication: return "EXTERNALLY_MANAGED_REPLICATION"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "READY": self = .ready
      case "UPDATING": self = .updating
      case "DELETING": self = .deleting
      case "ERROR": self = .error
      case "PENDING_CLUSTER_PEERING": self = .pendingClusterPeering
      case "PENDING_SVM_PEERING": self = .pendingSvmPeering
      case "PENDING_REMOTE_RESYNC": self = .pendingRemoteResync
      case "EXTERNALLY_MANAGED_REPLICATION": self = .externallyManagedReplication
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .ready
      case 3: self = .updating
      case 5: self = .deleting
      case 6: self = .error
      case 8: self = .pendingClusterPeering
      case 9: self = .pendingSvmPeering
      case 10: self = .pendingRemoteResync
      case 11: self = .externallyManagedReplication
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .creating: return try container.encode(1)
      case .ready: return try container.encode(2)
      case .updating: return try container.encode(3)
      case .deleting: return try container.encode(5)
      case .error: return try container.encode(6)
      case .pendingClusterPeering: return try container.encode(8)
      case .pendingSvmPeering: return try container.encode(9)
      case .pendingRemoteResync: return try container.encode(10)
      case .externallyManagedReplication: return try container.encode(11)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// New enum values may be added in future to support different replication
  /// topology.
  public enum ReplicationRole: Codable, Equatable, Sendable {
    /// Unspecified replication role
    case unspecified
    /// Indicates Source volume.
    case source
    /// Indicates Destination volume.
    case destination
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .source: return 1
      case .destination: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "REPLICATION_ROLE_UNSPECIFIED"
      case .source: return "SOURCE"
      case .destination: return "DESTINATION"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ReplicationRole/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "REPLICATION_ROLE_UNSPECIFIED": self = .unspecified
      case "SOURCE": self = .source
      case "DESTINATION": self = .destination
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ReplicationRole/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .source
      case 2: self = .destination
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .source: return try container.encode(1)
      case .destination: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Schedule for Replication.
  /// New enum values may be added in future to support different frequency of
  /// replication.
  public enum ReplicationSchedule: Codable, Equatable, Sendable {
    /// Unspecified ReplicationSchedule
    case unspecified
    /// Replication happens once every 10 minutes.
    case every10Minutes
    /// Replication happens once every hour.
    case hourly
    /// Replication happens once every day.
    case daily
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .every10Minutes: return 1
      case .hourly: return 2
      case .daily: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "REPLICATION_SCHEDULE_UNSPECIFIED"
      case .every10Minutes: return "EVERY_10_MINUTES"
      case .hourly: return "HOURLY"
      case .daily: return "DAILY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ReplicationSchedule/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "REPLICATION_SCHEDULE_UNSPECIFIED": self = .unspecified
      case "EVERY_10_MINUTES": self = .every10Minutes
      case "HOURLY": self = .hourly
      case "DAILY": self = .daily
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ReplicationSchedule/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .every10Minutes
      case 2: self = .hourly
      case 3: self = .daily
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .every10Minutes: return try container.encode(1)
      case .hourly: return try container.encode(2)
      case .daily: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Mirroring states.
  /// No new value is expected to be added in future.
  public enum MirrorState: Codable, Equatable, Sendable {
    /// Unspecified MirrorState
    case unspecified
    /// Destination volume is being prepared.
    case preparing
    /// Destination volume has been initialized and is ready to receive
    /// replication transfers.
    case mirrored
    /// Destination volume is not receiving replication transfers.
    case stopped
    /// Incremental replication is in progress.
    case transferring
    /// Baseline replication is in progress.
    case baselineTransferring
    /// Replication is aborted.
    case aborted
    /// Replication is being managed from Onprem ONTAP.
    case externallyManaged
    /// Peering is yet to be established.
    case pendingPeering
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .preparing: return 1
      case .mirrored: return 2
      case .stopped: return 3
      case .transferring: return 4
      case .baselineTransferring: return 5
      case .aborted: return 6
      case .externallyManaged: return 7
      case .pendingPeering: return 8
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "MIRROR_STATE_UNSPECIFIED"
      case .preparing: return "PREPARING"
      case .mirrored: return "MIRRORED"
      case .stopped: return "STOPPED"
      case .transferring: return "TRANSFERRING"
      case .baselineTransferring: return "BASELINE_TRANSFERRING"
      case .aborted: return "ABORTED"
      case .externallyManaged: return "EXTERNALLY_MANAGED"
      case .pendingPeering: return "PENDING_PEERING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:MirrorState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "MIRROR_STATE_UNSPECIFIED": self = .unspecified
      case "PREPARING": self = .preparing
      case "MIRRORED": self = .mirrored
      case "STOPPED": self = .stopped
      case "TRANSFERRING": self = .transferring
      case "BASELINE_TRANSFERRING": self = .baselineTransferring
      case "ABORTED": self = .aborted
      case "EXTERNALLY_MANAGED": self = .externallyManaged
      case "PENDING_PEERING": self = .pendingPeering
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:MirrorState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .preparing
      case 2: self = .mirrored
      case 3: self = .stopped
      case 4: self = .transferring
      case 5: self = .baselineTransferring
      case 6: self = .aborted
      case 7: self = .externallyManaged
      case 8: self = .pendingPeering
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .preparing: return try container.encode(1)
      case .mirrored: return try container.encode(2)
      case .stopped: return try container.encode(3)
      case .transferring: return try container.encode(4)
      case .baselineTransferring: return try container.encode(5)
      case .aborted: return try container.encode(6)
      case .externallyManaged: return try container.encode(7)
      case .pendingPeering: return try container.encode(8)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Hybrid replication type.
  public enum HybridReplicationType: Codable, Equatable, Sendable {
    /// Unspecified hybrid replication type.
    case unspecified
    /// Hybrid replication type for migration.
    case migration
    /// Hybrid replication type for continuous replication.
    case continuousReplication
    /// New field for reversible OnPrem replication, to be used for data
    /// protection.
    case onpremReplication
    /// Hybrid replication type for incremental Transfer in the reverse direction
    /// (GCNV is source and Onprem is destination)
    case reverseOnpremReplication
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .migration: return 1
      case .continuousReplication: return 2
      case .onpremReplication: return 3
      case .reverseOnpremReplication: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "HYBRID_REPLICATION_TYPE_UNSPECIFIED"
      case .migration: return "MIGRATION"
      case .continuousReplication: return "CONTINUOUS_REPLICATION"
      case .onpremReplication: return "ONPREM_REPLICATION"
      case .reverseOnpremReplication: return "REVERSE_ONPREM_REPLICATION"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:HybridReplicationType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "HYBRID_REPLICATION_TYPE_UNSPECIFIED": self = .unspecified
      case "MIGRATION": self = .migration
      case "CONTINUOUS_REPLICATION": self = .continuousReplication
      case "ONPREM_REPLICATION": self = .onpremReplication
      case "REVERSE_ONPREM_REPLICATION": self = .reverseOnpremReplication
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:HybridReplicationType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .migration
      case 2: self = .continuousReplication
      case 3: self = .onpremReplication
      case 4: self = .reverseOnpremReplication
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .migration: return try container.encode(1)
      case .continuousReplication: return try container.encode(2)
      case .onpremReplication: return try container.encode(3)
      case .reverseOnpremReplication: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.netapp.v1.Replication"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
