// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The RestoreParameters if volume is created from a snapshot or backup.
public struct RestoreParameters: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The source that the volume is created from.
  public var source: OneOf_Source? = nil

  /// Initialize a new instance of `RestoreParameters`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RestoreParameters().with { $0.sourceSnapshot = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case sourceSnapshot = "sourceSnapshot"
    case sourceBackup = "sourceBackup"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var source: OneOf_Source? = nil
    let sourceCheckAndSet = {
      if source != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'source'"))
      }
      source = $0
    }
    if let sourceSnapshot = try container.decodeIfPresent(
      Swift.String.self, forKey: .sourceSnapshot)
    {
      try sourceCheckAndSet(.sourceSnapshot(sourceSnapshot))
    }
    if let sourceBackup = try container.decodeIfPresent(Swift.String.self, forKey: .sourceBackup) {
      try sourceCheckAndSet(.sourceBackup(sourceBackup))
    }
    self.source = source
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.source {
      switch choice {
      case .sourceSnapshot(let value):
        try container.encode(value, forKey: .sourceSnapshot)
      case .sourceBackup(let value):
        try container.encode(value, forKey: .sourceBackup)
      }
    }
  }

  /// The source that the volume is created from.
  public enum OneOf_Source: Codable, Equatable, Sendable {
    /// Full name of the snapshot resource.
    /// Format:
    /// projects/{project}/locations/{location}/volumes/{volume}/snapshots/{snapshot}
    case sourceSnapshot(Swift.String)
    /// Full name of the backup resource.
    /// Format for standard backup:
    /// projects/{project}/locations/{location}/backupVaults/{backup_vault_id}/backups/{backup_id}
    /// Format for BackupDR backup:
    /// projects/{project}/locations/{location}/backupVaults/{backup_vault}/dataSources/{data_source}/backups/{backup}
    case sourceBackup(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.netapp.v1.RestoreParameters"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
