// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// An export policy rule describing various export options.
public struct SimpleExportPolicyRule: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Comma separated list of allowed clients IP addresses
  public var allowedClients: Swift.String? = nil

  /// Whether Unix root access will be granted.
  public var hasRootAccess: Swift.String? = nil

  /// Access type (ReadWrite, ReadOnly, None)
  public var accessType: AccessType? = nil

  /// NFS V3 protocol.
  public var nfsv3: Swift.Bool? = nil

  /// NFS V4 protocol.
  public var nfsv4: Swift.Bool? = nil

  /// If enabled (true) the rule defines a read only access for clients matching
  /// the 'allowedClients' specification. It enables nfs clients to mount using
  /// 'authentication' kerberos security mode.
  public var kerberos5ReadOnly: Swift.Bool? = nil

  /// If enabled (true) the rule defines read and write access for clients
  /// matching the 'allowedClients' specification. It enables nfs clients to
  /// mount using 'authentication' kerberos security mode. The
  /// 'kerberos5ReadOnly' value be ignored if this is enabled.
  public var kerberos5ReadWrite: Swift.Bool? = nil

  /// If enabled (true) the rule defines a read only access for clients matching
  /// the 'allowedClients' specification. It enables nfs clients to mount using
  /// 'integrity' kerberos security mode.
  public var kerberos5IReadOnly: Swift.Bool? = nil

  /// If enabled (true) the rule defines read and write access for clients
  /// matching the 'allowedClients' specification. It enables nfs clients to
  /// mount using 'integrity' kerberos security mode. The 'kerberos5iReadOnly'
  /// value be ignored if this is enabled.
  public var kerberos5IReadWrite: Swift.Bool? = nil

  /// If enabled (true) the rule defines a read only access for clients matching
  /// the 'allowedClients' specification. It enables nfs clients to mount using
  /// 'privacy' kerberos security mode.
  public var kerberos5PReadOnly: Swift.Bool? = nil

  /// If enabled (true) the rule defines read and write access for clients
  /// matching the 'allowedClients' specification. It enables nfs clients to
  /// mount using 'privacy' kerberos security mode. The 'kerberos5pReadOnly'
  /// value be ignored if this is enabled.
  public var kerberos5PReadWrite: Swift.Bool? = nil

  /// Optional. Defines how user identity squashing is applied for this export
  /// rule. This field is the preferred way to configure squashing behavior and
  /// takes precedence over `has_root_access` if both are provided.
  public var squashMode: SimpleExportPolicyRule.SquashMode? = nil

  /// Optional. An integer representing the anonymous user ID. Range is 0 to
  /// `4294967295`. Required when `squash_mode` is `ROOT_SQUASH` or `ALL_SQUASH`.
  public var anonUid: Swift.Int64? = nil

  /// Initialize a new instance of `SimpleExportPolicyRule`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SimpleExportPolicyRule().with { $0.allowedClients = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case allowedClients = "allowedClients"
    case hasRootAccess = "hasRootAccess"
    case accessType = "accessType"
    case nfsv3 = "nfsv3"
    case nfsv4 = "nfsv4"
    case kerberos5ReadOnly = "kerberos5ReadOnly"
    case kerberos5ReadWrite = "kerberos5ReadWrite"
    case kerberos5IReadOnly = "kerberos5iReadOnly"
    case kerberos5IReadWrite = "kerberos5iReadWrite"
    case kerberos5PReadOnly = "kerberos5pReadOnly"
    case kerberos5PReadWrite = "kerberos5pReadWrite"
    case squashMode = "squashMode"
    case anonUid = "anonUid"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.allowedClients = try container.decodeIfPresent(Swift.String.self, forKey: .allowedClients)
    self.hasRootAccess = try container.decodeIfPresent(Swift.String.self, forKey: .hasRootAccess)
    self.accessType = try container.decodeIfPresent(AccessType.self, forKey: .accessType)
    self.nfsv3 = try container.decodeIfPresent(Swift.Bool.self, forKey: .nfsv3)
    self.nfsv4 = try container.decodeIfPresent(Swift.Bool.self, forKey: .nfsv4)
    self.kerberos5ReadOnly = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .kerberos5ReadOnly)
    self.kerberos5ReadWrite = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .kerberos5ReadWrite)
    self.kerberos5IReadOnly = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .kerberos5IReadOnly)
    self.kerberos5IReadWrite = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .kerberos5IReadWrite)
    self.kerberos5PReadOnly = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .kerberos5PReadOnly)
    self.kerberos5PReadWrite = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .kerberos5PReadWrite)
    self.squashMode = try container.decodeIfPresent(
      SimpleExportPolicyRule.SquashMode.self, forKey: .squashMode)
    self.anonUid = try container.decodeIfPresent(Swift.Int64.self, forKey: .anonUid)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.allowedClients, forKey: .allowedClients)
    try container.encode(self.hasRootAccess, forKey: .hasRootAccess)
    try container.encode(self.accessType, forKey: .accessType)
    try container.encode(self.nfsv3, forKey: .nfsv3)
    try container.encode(self.nfsv4, forKey: .nfsv4)
    try container.encode(self.kerberos5ReadOnly, forKey: .kerberos5ReadOnly)
    try container.encode(self.kerberos5ReadWrite, forKey: .kerberos5ReadWrite)
    try container.encode(self.kerberos5IReadOnly, forKey: .kerberos5IReadOnly)
    try container.encode(self.kerberos5IReadWrite, forKey: .kerberos5IReadWrite)
    try container.encode(self.kerberos5PReadOnly, forKey: .kerberos5PReadOnly)
    try container.encode(self.kerberos5PReadWrite, forKey: .kerberos5PReadWrite)
    try container.encode(self.squashMode, forKey: .squashMode)
    try container.encode(self.anonUid, forKey: .anonUid)
  }

  /// `SquashMode` defines how remote user privileges are restricted when
  /// accessing an NFS export. It controls how user identities (like root) are
  /// mapped to anonymous users to limit access and enforce security.
  public enum SquashMode: Codable, Equatable, Sendable {
    /// Defaults to `NO_ROOT_SQUASH`.
    case unspecified
    /// The root user (UID 0) retains full access. Other users are
    /// unaffected.
    case noRootSquash
    /// The root user (UID 0) is squashed to anonymous user ID. Other users are
    /// unaffected.
    case rootSquash
    /// All users are squashed to anonymous user ID.
    case allSquash
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .noRootSquash: return 1
      case .rootSquash: return 2
      case .allSquash: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SQUASH_MODE_UNSPECIFIED"
      case .noRootSquash: return "NO_ROOT_SQUASH"
      case .rootSquash: return "ROOT_SQUASH"
      case .allSquash: return "ALL_SQUASH"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:SquashMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SQUASH_MODE_UNSPECIFIED": self = .unspecified
      case "NO_ROOT_SQUASH": self = .noRootSquash
      case "ROOT_SQUASH": self = .rootSquash
      case "ALL_SQUASH": self = .allSquash
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:SquashMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .noRootSquash
      case 2: self = .rootSquash
      case 3: self = .allSquash
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .noRootSquash: return try container.encode(1)
      case .rootSquash: return try container.encode(2)
      case .allSquash: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.netapp.v1.SimpleExportPolicyRule"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
