// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// SMBSettings
/// Modifies the behaviour of a SMB volume.
public enum SMBSettings: Codable, Equatable, Sendable {
  /// Unspecified default option
  case unspecified
  /// SMB setting encrypt data
  case encryptData
  /// SMB setting browsable
  case browsable
  /// SMB setting notify change
  case changeNotify
  /// SMB setting not to notify change
  case nonBrowsable
  /// SMB setting oplocks
  case oplocks
  /// SMB setting to show snapshots
  case showSnapshot
  /// SMB setting to show previous versions
  case showPreviousVersions
  /// SMB setting to access volume based on enumerartion
  case accessBasedEnumeration
  /// Continuously available enumeration
  case continuouslyAvailable
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .encryptData: return 1
    case .browsable: return 2
    case .changeNotify: return 3
    case .nonBrowsable: return 4
    case .oplocks: return 5
    case .showSnapshot: return 6
    case .showPreviousVersions: return 7
    case .accessBasedEnumeration: return 8
    case .continuouslyAvailable: return 9
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "SMB_SETTINGS_UNSPECIFIED"
    case .encryptData: return "ENCRYPT_DATA"
    case .browsable: return "BROWSABLE"
    case .changeNotify: return "CHANGE_NOTIFY"
    case .nonBrowsable: return "NON_BROWSABLE"
    case .oplocks: return "OPLOCKS"
    case .showSnapshot: return "SHOW_SNAPSHOT"
    case .showPreviousVersions: return "SHOW_PREVIOUS_VERSIONS"
    case .accessBasedEnumeration: return "ACCESS_BASED_ENUMERATION"
    case .continuouslyAvailable: return "CONTINUOUSLY_AVAILABLE"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:SMBSettings/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "SMB_SETTINGS_UNSPECIFIED": self = .unspecified
    case "ENCRYPT_DATA": self = .encryptData
    case "BROWSABLE": self = .browsable
    case "CHANGE_NOTIFY": self = .changeNotify
    case "NON_BROWSABLE": self = .nonBrowsable
    case "OPLOCKS": self = .oplocks
    case "SHOW_SNAPSHOT": self = .showSnapshot
    case "SHOW_PREVIOUS_VERSIONS": self = .showPreviousVersions
    case "ACCESS_BASED_ENUMERATION": self = .accessBasedEnumeration
    case "CONTINUOUSLY_AVAILABLE": self = .continuouslyAvailable
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:SMBSettings/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .encryptData
    case 2: self = .browsable
    case 3: self = .changeNotify
    case 4: self = .nonBrowsable
    case 5: self = .oplocks
    case 6: self = .showSnapshot
    case 7: self = .showPreviousVersions
    case 8: self = .accessBasedEnumeration
    case 9: self = .continuouslyAvailable
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .encryptData: return try container.encode(1)
    case .browsable: return try container.encode(2)
    case .changeNotify: return try container.encode(3)
    case .nonBrowsable: return try container.encode(4)
    case .oplocks: return try container.encode(5)
    case .showSnapshot: return try container.encode(6)
    case .showPreviousVersions: return try container.encode(7)
    case .accessBasedEnumeration: return try container.encode(8)
    case .continuouslyAvailable: return try container.encode(9)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
