// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Snapshot is a point-in-time version of a Volume's content.
public struct Snapshot: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Identifier. The resource name of the snapshot.
  /// Format:
  /// `projects/{project_id}/locations/{location}/volumes/{volume_id}/snapshots/{snapshot_id}`.
  public var name: Swift.String = Swift.String()

  /// Output only. The snapshot state.
  public var state: Snapshot.State = Snapshot.State()

  /// Output only. State details of the storage pool
  public var stateDetails: Swift.String = Swift.String()

  /// A description of the snapshot with 2048 characters or less.
  /// Requests with longer descriptions will be rejected.
  public var description: Swift.String = Swift.String()

  /// Output only. Current storage usage for the snapshot in bytes.
  public var usedBytes: Swift.Double = Swift.Double()

  /// Output only. The time when the snapshot was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Resource labels to represent user provided metadata.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Initialize a new instance of `Snapshot`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Snapshot().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The Snapshot States
  public enum State: Codable, Equatable, Sendable {
    /// Unspecified Snapshot State
    case unspecified
    /// Snapshot State is Ready
    case ready
    /// Snapshot State is Creating
    case creating
    /// Snapshot State is Deleting
    case deleting
    /// Snapshot State is Updating
    case updating
    /// Snapshot State is Disabled
    case disabled
    /// Snapshot State is Error
    case error
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .ready: return 1
      case .creating: return 2
      case .deleting: return 3
      case .updating: return 4
      case .disabled: return 5
      case .error: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .ready: return "READY"
      case .creating: return "CREATING"
      case .deleting: return "DELETING"
      case .updating: return "UPDATING"
      case .disabled: return "DISABLED"
      case .error: return "ERROR"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "READY": self = .ready
      case "CREATING": self = .creating
      case "DELETING": self = .deleting
      case "UPDATING": self = .updating
      case "DISABLED": self = .disabled
      case "ERROR": self = .error
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .ready
      case 2: self = .creating
      case 3: self = .deleting
      case 4: self = .updating
      case 5: self = .disabled
      case 6: self = .error
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .ready: return try container.encode(1)
      case .creating: return try container.encode(2)
      case .deleting: return try container.encode(3)
      case .updating: return try container.encode(4)
      case .disabled: return try container.encode(5)
      case .error: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.netapp.v1.Snapshot"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
