// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Snapshot Policy for a volume.
public struct SnapshotPolicy: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// If enabled, make snapshots automatically according to the schedules.
  /// Default is false.
  public var enabled: Swift.Bool? = nil

  /// Hourly schedule policy.
  public var hourlySchedule: HourlySchedule? = nil

  /// Daily schedule policy.
  public var dailySchedule: DailySchedule? = nil

  /// Weekly schedule policy.
  public var weeklySchedule: WeeklySchedule? = nil

  /// Monthly schedule policy.
  public var monthlySchedule: MonthlySchedule? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SnapshotPolicy`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SnapshotPolicy().with { $0.enabled = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let enabled = CodingKeys(stringValue: "enabled")
    static let hourlySchedule = CodingKeys(stringValue: "hourlySchedule")
    static let dailySchedule = CodingKeys(stringValue: "dailySchedule")
    static let weeklySchedule = CodingKeys(stringValue: "weeklySchedule")
    static let monthlySchedule = CodingKeys(stringValue: "monthlySchedule")

    static let _knownKeys: Set<Swift.String> = [
      "enabled",
      "hourlySchedule",
      "dailySchedule",
      "weeklySchedule",
      "monthlySchedule",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.enabled = try container.decodeIfPresent(Swift.Bool.self, forKey: .enabled)
    self.hourlySchedule = try container.decodeIfPresent(
      HourlySchedule.self, forKey: .hourlySchedule)
    self.dailySchedule = try container.decodeIfPresent(DailySchedule.self, forKey: .dailySchedule)
    self.weeklySchedule = try container.decodeIfPresent(
      WeeklySchedule.self, forKey: .weeklySchedule)
    self.monthlySchedule = try container.decodeIfPresent(
      MonthlySchedule.self, forKey: .monthlySchedule)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.enabled, forKey: .enabled)
    try container.encodeIfPresent(self.hourlySchedule, forKey: .hourlySchedule)
    try container.encodeIfPresent(self.dailySchedule, forKey: .dailySchedule)
    try container.encodeIfPresent(self.weeklySchedule, forKey: .weeklySchedule)
    try container.encodeIfPresent(self.monthlySchedule, forKey: .monthlySchedule)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.netapp.v1.SnapshotPolicy"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
