// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Snapshot Policy for a volume.
public struct SnapshotPolicy: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// If enabled, make snapshots automatically according to the schedules.
  /// Default is false.
  public var enabled: Swift.Bool? = nil

  /// Hourly schedule policy.
  public var hourlySchedule: HourlySchedule? = nil

  /// Daily schedule policy.
  public var dailySchedule: DailySchedule? = nil

  /// Weekly schedule policy.
  public var weeklySchedule: WeeklySchedule? = nil

  /// Monthly schedule policy.
  public var monthlySchedule: MonthlySchedule? = nil

  /// Initialize a new instance of `SnapshotPolicy`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SnapshotPolicy().with { $0.enabled = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.netapp.v1.SnapshotPolicy"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
