// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// StoragePool is a container for volumes with a service level and capacity.
/// Volumes can be created in a pool of sufficient available capacity.
/// StoragePool capacity is what you are billed for.
public struct StoragePool: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. Name of the storage pool
  public var name: Swift.String = Swift.String()

  /// Required. Service level of the storage pool
  public var serviceLevel: ServiceLevel = ServiceLevel()

  /// Required. Capacity in GIB of the pool
  public var capacityGib: Swift.Int64 = Swift.Int64()

  /// Output only. Allocated size of all volumes in GIB in the storage pool
  public var volumeCapacityGib: Swift.Int64 = Swift.Int64()

  /// Output only. Volume count of the storage pool
  public var volumeCount: Swift.Int32 = Swift.Int32()

  /// Output only. State of the storage pool
  public var state: StoragePool.State = StoragePool.State()

  /// Output only. State details of the storage pool
  public var stateDetails: Swift.String = Swift.String()

  /// Output only. Create time of the storage pool
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Optional. Description of the storage pool
  public var description: Swift.String = Swift.String()

  /// Optional. Labels as key value pairs
  public var labels: [Swift.String: Swift.String] = [:]

  /// Required. VPC Network name.
  /// Format: projects/{project}/global/networks/{network}
  public var network: Swift.String = Swift.String()

  /// Optional. Specifies the Active Directory to be used for creating a SMB
  /// volume.
  public var activeDirectory: Swift.String = Swift.String()

  /// Optional. Specifies the KMS config to be used for volume encryption.
  public var kmsConfig: Swift.String = Swift.String()

  /// Optional. Flag indicating if the pool is NFS LDAP enabled or not.
  public var ldapEnabled: Swift.Bool = Swift.Bool()

  /// Optional. This field is not implemented. The values provided in this field
  /// are ignored.
  public var psaRange: Swift.String = Swift.String()

  /// Output only. Specifies the current pool encryption key source.
  public var encryptionType: EncryptionType = EncryptionType()

  /// Deprecated. Used to allow SO pool to access AD or DNS server from other
  /// regions.
  @available(*, deprecated)
  public var globalAccessAllowed: Swift.Bool? = nil

  /// Optional. True if the storage pool supports Auto Tiering enabled volumes.
  /// Default is false. Auto-tiering can be enabled after storage pool creation
  /// but it can't be disabled once enabled.
  public var allowAutoTiering: Swift.Bool = Swift.Bool()

  /// Optional. Specifies the replica zone for regional storagePool.
  public var replicaZone: Swift.String = Swift.String()

  /// Optional. Specifies the active zone for regional storagePool.
  public var zone: Swift.String = Swift.String()

  /// Output only. Reserved for future use
  public var satisfiesPzs: Swift.Bool = Swift.Bool()

  /// Output only. Reserved for future use
  public var satisfiesPzi: Swift.Bool = Swift.Bool()

  /// Optional. True if using Independent Scaling of capacity and performance
  /// (Hyperdisk) By default set to false
  public var customPerformanceEnabled: Swift.Bool = Swift.Bool()

  /// Optional. Custom Performance Total Throughput of the pool (in MiBps)
  public var totalThroughputMibps: Swift.Int64 = Swift.Int64()

  /// Optional. Custom Performance Total IOPS of the pool
  /// if not provided, it will be calculated based on the total_throughput_mibps
  public var totalIops: Swift.Int64 = Swift.Int64()

  /// Optional. Total hot tier capacity for the Storage Pool. It is applicable
  /// only to Flex service level. It should be less than the minimum storage pool
  /// size and cannot be more than the current storage pool size. It cannot be
  /// decreased once set.
  public var hotTierSizeGib: Swift.Int64 = Swift.Int64()

  /// Optional. Flag indicating that the hot-tier threshold will be
  /// auto-increased by 10% of the hot-tier when it hits 100%. Default is true.
  /// The increment will kick in only if the new size after increment is
  /// still less than or equal to storage pool size.
  public var enableHotTierAutoResize: Swift.Bool? = nil

  /// Optional. QoS (Quality of Service) Type of the storage pool
  public var qosType: QosType = QosType()

  /// Output only. Available throughput of the storage pool (in MiB/s).
  public var availableThroughputMibps: Swift.Double = Swift.Double()

  /// Output only. Total cold tier data rounded down to the nearest GiB used by
  /// the storage pool.
  public var coldTierSizeUsedGib: Swift.Int64 = Swift.Int64()

  /// Output only. Total hot tier data rounded down to the nearest GiB used by
  /// the storage pool.
  public var hotTierSizeUsedGib: Swift.Int64 = Swift.Int64()

  /// Optional. Type of the storage pool. This field is used to control whether
  /// the pool supports `FILE` based volumes only or `UNIFIED` (both `FILE` and
  /// `BLOCK`) volumes. If not specified during creation, it defaults to `FILE`.
  public var type: StoragePoolType? = nil

  /// Optional. Mode of the storage pool. This field is used to control whether
  /// the user can perform the ONTAP operations on the storage pool using the
  /// GCNV ONTAP Mode APIs. If not specified during creation, it defaults to
  /// `DEFAULT`.
  public var mode: Mode? = nil

  /// Optional. The scale type of the storage pool. Defaults to
  /// `SCALE_TYPE_DEFAULT` if not specified.
  public var scaleType: ScaleType = ScaleType()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `StoragePool`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StoragePool().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let serviceLevel = CodingKeys(stringValue: "serviceLevel")
    static let capacityGib = CodingKeys(stringValue: "capacityGib")
    static let volumeCapacityGib = CodingKeys(stringValue: "volumeCapacityGib")
    static let volumeCount = CodingKeys(stringValue: "volumeCount")
    static let state = CodingKeys(stringValue: "state")
    static let stateDetails = CodingKeys(stringValue: "stateDetails")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let description = CodingKeys(stringValue: "description")
    static let labels = CodingKeys(stringValue: "labels")
    static let network = CodingKeys(stringValue: "network")
    static let activeDirectory = CodingKeys(stringValue: "activeDirectory")
    static let kmsConfig = CodingKeys(stringValue: "kmsConfig")
    static let ldapEnabled = CodingKeys(stringValue: "ldapEnabled")
    static let psaRange = CodingKeys(stringValue: "psaRange")
    static let encryptionType = CodingKeys(stringValue: "encryptionType")
    static let globalAccessAllowed = CodingKeys(stringValue: "globalAccessAllowed")
    static let allowAutoTiering = CodingKeys(stringValue: "allowAutoTiering")
    static let replicaZone = CodingKeys(stringValue: "replicaZone")
    static let zone = CodingKeys(stringValue: "zone")
    static let satisfiesPzs = CodingKeys(stringValue: "satisfiesPzs")
    static let satisfiesPzi = CodingKeys(stringValue: "satisfiesPzi")
    static let customPerformanceEnabled = CodingKeys(stringValue: "customPerformanceEnabled")
    static let totalThroughputMibps = CodingKeys(stringValue: "totalThroughputMibps")
    static let totalIops = CodingKeys(stringValue: "totalIops")
    static let hotTierSizeGib = CodingKeys(stringValue: "hotTierSizeGib")
    static let enableHotTierAutoResize = CodingKeys(stringValue: "enableHotTierAutoResize")
    static let qosType = CodingKeys(stringValue: "qosType")
    static let availableThroughputMibps = CodingKeys(stringValue: "availableThroughputMibps")
    static let coldTierSizeUsedGib = CodingKeys(stringValue: "coldTierSizeUsedGib")
    static let hotTierSizeUsedGib = CodingKeys(stringValue: "hotTierSizeUsedGib")
    static let type = CodingKeys(stringValue: "type")
    static let mode = CodingKeys(stringValue: "mode")
    static let scaleType = CodingKeys(stringValue: "scaleType")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "serviceLevel",
      "capacityGib",
      "volumeCapacityGib",
      "volumeCount",
      "state",
      "stateDetails",
      "createTime",
      "description",
      "labels",
      "network",
      "activeDirectory",
      "kmsConfig",
      "ldapEnabled",
      "psaRange",
      "encryptionType",
      "globalAccessAllowed",
      "allowAutoTiering",
      "replicaZone",
      "zone",
      "satisfiesPzs",
      "satisfiesPzi",
      "customPerformanceEnabled",
      "totalThroughputMibps",
      "totalIops",
      "hotTierSizeGib",
      "enableHotTierAutoResize",
      "qosType",
      "availableThroughputMibps",
      "coldTierSizeUsedGib",
      "hotTierSizeUsedGib",
      "type",
      "mode",
      "scaleType",
    ]
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(ServiceLevel.self, forKey: .serviceLevel) {
      self.serviceLevel = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .capacityGib) {
      self.capacityGib = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .volumeCapacityGib) {
      self.volumeCapacityGib = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .volumeCount) {
      self.volumeCount = value
    }
    if let value = try container.decodeIfPresent(StoragePool.State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .stateDetails) {
      self.stateDetails = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .network) {
      self.network = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .activeDirectory) {
      self.activeDirectory = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .kmsConfig) {
      self.kmsConfig = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .ldapEnabled) {
      self.ldapEnabled = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .psaRange) {
      self.psaRange = value
    }
    if let value = try container.decodeIfPresent(EncryptionType.self, forKey: .encryptionType) {
      self.encryptionType = value
    }
    self.globalAccessAllowed = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .globalAccessAllowed)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .allowAutoTiering) {
      self.allowAutoTiering = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .replicaZone) {
      self.replicaZone = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .zone) {
      self.zone = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .satisfiesPzs) {
      self.satisfiesPzs = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .satisfiesPzi) {
      self.satisfiesPzi = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .customPerformanceEnabled)
    {
      self.customPerformanceEnabled = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .totalThroughputMibps) {
      self.totalThroughputMibps = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .totalIops) {
      self.totalIops = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .hotTierSizeGib) {
      self.hotTierSizeGib = value
    }
    self.enableHotTierAutoResize = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .enableHotTierAutoResize)
    if let value = try container.decodeIfPresent(QosType.self, forKey: .qosType) {
      self.qosType = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Double.self, forKey: .availableThroughputMibps)
    {
      self.availableThroughputMibps = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .coldTierSizeUsedGib) {
      self.coldTierSizeUsedGib = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .hotTierSizeUsedGib) {
      self.hotTierSizeUsedGib = value
    }
    self.type = try container.decodeIfPresent(StoragePoolType.self, forKey: .type)
    self.mode = try container.decodeIfPresent(Mode.self, forKey: .mode)
    if let value = try container.decodeIfPresent(ScaleType.self, forKey: .scaleType) {
      self.scaleType = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.serviceLevel, forKey: .serviceLevel)
    try container.encode(self.capacityGib, forKey: .capacityGib)
    try container.encode(self.volumeCapacityGib, forKey: .volumeCapacityGib)
    try container.encode(self.volumeCount, forKey: .volumeCount)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.stateDetails, forKey: .stateDetails)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.network, forKey: .network)
    try container.encode(self.activeDirectory, forKey: .activeDirectory)
    try container.encode(self.kmsConfig, forKey: .kmsConfig)
    try container.encode(self.ldapEnabled, forKey: .ldapEnabled)
    try container.encode(self.psaRange, forKey: .psaRange)
    try container.encode(self.encryptionType, forKey: .encryptionType)
    try container.encodeIfPresent(self.globalAccessAllowed, forKey: .globalAccessAllowed)
    try container.encode(self.allowAutoTiering, forKey: .allowAutoTiering)
    try container.encode(self.replicaZone, forKey: .replicaZone)
    try container.encode(self.zone, forKey: .zone)
    try container.encode(self.satisfiesPzs, forKey: .satisfiesPzs)
    try container.encode(self.satisfiesPzi, forKey: .satisfiesPzi)
    try container.encode(self.customPerformanceEnabled, forKey: .customPerformanceEnabled)
    try container.encode(self.totalThroughputMibps, forKey: .totalThroughputMibps)
    try container.encode(self.totalIops, forKey: .totalIops)
    try container.encode(self.hotTierSizeGib, forKey: .hotTierSizeGib)
    try container.encodeIfPresent(self.enableHotTierAutoResize, forKey: .enableHotTierAutoResize)
    try container.encode(self.qosType, forKey: .qosType)
    try container.encode(self.availableThroughputMibps, forKey: .availableThroughputMibps)
    try container.encode(self.coldTierSizeUsedGib, forKey: .coldTierSizeUsedGib)
    try container.encode(self.hotTierSizeUsedGib, forKey: .hotTierSizeUsedGib)
    try container.encodeIfPresent(self.type, forKey: .type)
    try container.encodeIfPresent(self.mode, forKey: .mode)
    try container.encode(self.scaleType, forKey: .scaleType)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The Storage Pool States
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Sendable {
    /// Unspecified Storage Pool State
    case unspecified
    /// Storage Pool State is Ready
    case ready
    /// Storage Pool State is Creating
    case creating
    /// Storage Pool State is Deleting
    case deleting
    /// Storage Pool State is Updating
    case updating
    /// Storage Pool State is Restoring
    case restoring
    /// Storage Pool State is Disabled
    case disabled
    /// Storage Pool State is Error
    case error
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .ready: return 1
      case .creating: return 2
      case .deleting: return 3
      case .updating: return 4
      case .restoring: return 5
      case .disabled: return 6
      case .error: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .ready: return "READY"
      case .creating: return "CREATING"
      case .deleting: return "DELETING"
      case .updating: return "UPDATING"
      case .restoring: return "RESTORING"
      case .disabled: return "DISABLED"
      case .error: return "ERROR"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "READY": self = .ready
      case "CREATING": self = .creating
      case "DELETING": self = .deleting
      case "UPDATING": self = .updating
      case "RESTORING": self = .restoring
      case "DISABLED": self = .disabled
      case "ERROR": self = .error
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .ready
      case 2: self = .creating
      case 3: self = .deleting
      case 4: self = .updating
      case 5: self = .restoring
      case 6: self = .disabled
      case 7: self = .error
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .ready: return try container.encode("READY")
      case .creating: return try container.encode("CREATING")
      case .deleting: return try container.encode("DELETING")
      case .updating: return try container.encode("UPDATING")
      case .restoring: return try container.encode("RESTORING")
      case .disabled: return try container.encode("DISABLED")
      case .error: return try container.encode("ERROR")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.netapp.v1.StoragePool"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
