// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// TransferStats reports all statistics related to replication transfer.
public struct TransferStats: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Cumulative bytes transferred so far for the replication relationship.
  public var transferBytes: Swift.Int64? = nil

  /// Cumulative time taken across all transfers for the replication
  /// relationship.
  public var totalTransferDuration: GoogleCloudWkt.Duration? = nil

  /// Last transfer size in bytes.
  public var lastTransferBytes: Swift.Int64? = nil

  /// Time taken during last transfer.
  public var lastTransferDuration: GoogleCloudWkt.Duration? = nil

  /// Lag duration indicates the duration by which Destination region volume
  /// content lags behind the primary region volume content.
  public var lagDuration: GoogleCloudWkt.Duration? = nil

  /// Time when progress was updated last.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Time when last transfer completed.
  public var lastTransferEndTime: GoogleCloudWkt.Timestamp? = nil

  /// A message describing the cause of the last transfer failure.
  public var lastTransferError: Swift.String? = nil

  /// Initialize a new instance of `TransferStats`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TransferStats().with { $0.transferBytes = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.netapp.v1.TransferStats"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
