// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// TransferStats reports all statistics related to replication transfer.
public struct TransferStats: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Cumulative bytes transferred so far for the replication relationship.
  public var transferBytes: Swift.Int64? = nil

  /// Cumulative time taken across all transfers for the replication
  /// relationship.
  public var totalTransferDuration: GoogleWKT.WKTDuration? = nil

  /// Last transfer size in bytes.
  public var lastTransferBytes: Swift.Int64? = nil

  /// Time taken during last transfer.
  public var lastTransferDuration: GoogleWKT.WKTDuration? = nil

  /// Lag duration indicates the duration by which Destination region volume
  /// content lags behind the primary region volume content.
  public var lagDuration: GoogleWKT.WKTDuration? = nil

  /// Time when progress was updated last.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Time when last transfer completed.
  public var lastTransferEndTime: GoogleWKT.WKTTimestamp? = nil

  /// A message describing the cause of the last transfer failure.
  public var lastTransferError: Swift.String? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `TransferStats`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TransferStats().with { $0.transferBytes = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let transferBytes = CodingKeys(stringValue: "transferBytes")
    static let totalTransferDuration = CodingKeys(stringValue: "totalTransferDuration")
    static let lastTransferBytes = CodingKeys(stringValue: "lastTransferBytes")
    static let lastTransferDuration = CodingKeys(stringValue: "lastTransferDuration")
    static let lagDuration = CodingKeys(stringValue: "lagDuration")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let lastTransferEndTime = CodingKeys(stringValue: "lastTransferEndTime")
    static let lastTransferError = CodingKeys(stringValue: "lastTransferError")

    static let _knownKeys: Set<Swift.String> = [
      "transferBytes",
      "totalTransferDuration",
      "lastTransferBytes",
      "lastTransferDuration",
      "lagDuration",
      "updateTime",
      "lastTransferEndTime",
      "lastTransferError",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.transferBytes = try container.decodeIfPresent(Swift.Int64.self, forKey: .transferBytes)
    self.totalTransferDuration = try container.decodeIfPresent(
      GoogleWKT.WKTDuration.self, forKey: .totalTransferDuration)
    self.lastTransferBytes = try container.decodeIfPresent(
      Swift.Int64.self, forKey: .lastTransferBytes)
    self.lastTransferDuration = try container.decodeIfPresent(
      GoogleWKT.WKTDuration.self, forKey: .lastTransferDuration)
    self.lagDuration = try container.decodeIfPresent(
      GoogleWKT.WKTDuration.self, forKey: .lagDuration)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    self.lastTransferEndTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .lastTransferEndTime)
    self.lastTransferError = try container.decodeIfPresent(
      Swift.String.self, forKey: .lastTransferError)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.transferBytes, forKey: .transferBytes)
    try container.encodeIfPresent(self.totalTransferDuration, forKey: .totalTransferDuration)
    try container.encodeIfPresent(self.lastTransferBytes, forKey: .lastTransferBytes)
    try container.encodeIfPresent(self.lastTransferDuration, forKey: .lastTransferDuration)
    try container.encodeIfPresent(self.lagDuration, forKey: .lagDuration)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encodeIfPresent(self.lastTransferEndTime, forKey: .lastTransferEndTime)
    try container.encodeIfPresent(self.lastTransferError, forKey: .lastTransferError)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.netapp.v1.TransferStats"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
